thoth-station/adviser

- .coafile
- .zuul.yaml
Depends-On: https://github.com/thoth-station/zuul-test-jobs/pull/13
> using thoth zuul jobs now

- Pipfile
- Pipfile.lock
- setup.py
Depends-On: https://github.com/thoth-station/adviser/pull/130/files
> Setup py tests

- thoth/adviser/python/solver.py
When multiple stacks were generated, there was an issue with same hashes being
used multiple times for different packages. This patch addresses the this issue
- when python solver implemented on top of graph database did resolution,
constructor of PackageVersion class was used with arguments from the original
package. This caused reference to the same list being passed to different
package of same name - the gathering of package hashes did checks for same list
reference.
> Fix hashes collision in generated Pipfile.locks

- thoth/adviser/python/dependency_graph.py
Related: https://github.com/thoth-station/storages/pull/551
> Take into account packages that are not installable into the given env

- thoth/adviser/isis.py
- thoth/adviser/python/scoring.py
This way we will not produce warnings in case of Isis is not used.
> Make sure Isis is a singleton

- thoth/adviser/python/advise.py
> Do not score more than requested number of latest stacks

- liveness.py
- openshift/job-adviser-template.yaml
- thoth/adviser/python/dependency_graph.py
> Introduce stack producer timeout

- thoth/adviser/isis.py
- thoth/adviser/python/scoring.py
* fix duplicate methods
* fix spelling in attributes
> Make Isis instance attribute

- openshift/buildConfig-template.yaml
- openshift/imageStream-template.yaml
- openshift/job-adviser-template.yaml
- openshift/job-dependencyMonkey-template.yaml
- openshift/job-provenanceChecker-template.yaml
put some sane default for IMAGE_STREAM_NAMESPACE into each template
this fixes #220 
> sane default for IMAGE_STREAM_NAMESPACE

- thoth/adviser/python/pipeline/pipeline.py
- thoth/adviser/python/solver.py
Depends-On: https://github.com/thoth-station/storages/pull/675
> Use new method to obtain even large stacks from graph database

- tests/python/pipeline/steps/test_buildtime_error.py
- tests/python/pipeline/steps/test_cve.py
- tests/python/pipeline/steps/test_limit_latest_versions.py
- tests/python/pipeline/steps/test_performance_adjustment.py
- tests/python/pipeline/steps/test_prereleases.py
- tests/python/pipeline/steps/test_restrict_indexes.py
- tests/python/pipeline/steps/test_semver_sort.py
- tests/python/pipeline/steps/test_toolchain.py
- tests/python/pipeline/steps/test_unreachable.py
- tests/python/pipeline/strides/test_cve.py
- tests/python/pipeline/strides/test_performance_scoring.py
- tests/python/pipeline/strides/test_random_decision.py
- tests/python/pipeline/strides/test_score_filter.py
- tests/python/pipeline/test_pipeline.py
- thoth/adviser/cli.py
- thoth/adviser/python/advise.py
- thoth/adviser/python/builder.py
- thoth/adviser/python/dependency_monkey.py
- thoth/adviser/python/pipeline/pipeline.py
- thoth/adviser/python/pipeline/step_context.py
This way we are able to dynamically create pipeline steps based on user's
runtime environment, library usage and libraries used.
> Create pipeline builder abstraction

- thoth/adviser/python/pipeline/step_context.py
This way we will not issue copying arrays of paths.
> Optimize package removal by working on indexes instead of package tuples

- README.rst
> Updated Readme to Dgraph examples

- .zuul.yaml
- openshift/buildConfig-template.yaml
Add generic trigger webhook to buildconfig
Add trigger build job to zuul post pipeline job list
> Add build trigger with generic webhook

- tests/graph_mock.py
- thoth/adviser/python/solver.py
Fixes: #303
Depends-On: https://github.com/thoth-station/storages/issues/798
> Use only packages with known index

- thoth/adviser/python/pipeline/pipeline.py
... so it's easier to read in in logs...
> Print out estimated number of stacks in scientific form

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> added the standard github configuration and a CODEOWNERS file

- thoth/adviser/cli.py
Fixes: https://github.com/thoth-station/thamos/issues/196
> Report error if no recommendation was produced

- thoth/adviser/cli.py
Depends-On: https://github.com/thoth-station/solver/issues/254
> Inform user that the missing release will be analyzed later on

- thoth/adviser/python/pipeline/steps/prereleases.py
> Do not treat builds as pre-releases

- docs/source/index.rst
- docs/source/integration.rst
I think we will need to place this somewhere more accessible (thoth-station.ninja preferably, but let's have it for now).
> State how to integrate with Thoth in docs

- thoth/adviser/cli.py
Fixes: https://github.com/thoth-station/adviser/issues/389
> Propagate runtime environment explicitly

- openshift/buildConfig-cached-template.yaml
- openshift/job-adviser-template.yaml
- openshift/job-dependencyMonkey-template.yaml
- openshift/job-provenanceChecker-template.yaml
... so that we distinguish differnet deployments
> Propagate deployment name for sentry environment

- README.rst
> Corrected typos

- tests/python/pipeline/sieves/test_limit_latest_versions.py
- tests/python/pipeline/test_sieve_context.py
- thoth/adviser/python/pipeline/sieve_context.py
- thoth/adviser/python/pipeline/sieves/__init__.py
- thoth/adviser/python/pipeline/sieves/limit_latest_versions.py
> Introduce sieve for limiting number of latest versions in direct dependencies

- tests/python/pipeline/sieves/test_prereleases.py
- thoth/adviser/python/pipeline/sieves/__init__.py
- thoth/adviser/python/pipeline/sieves/prereleases.py
> Add a new sieve for limiting pre-releases in direct dependencies

- tests/python/pipeline/sieves/test_semver_sort.py
- thoth/adviser/python/pipeline/sieves/semver_sort.py
> Introduce semver sorting on direct dependnecies - sieve

- thoth/adviser/python/builder.py
As the current index structure was adjusted, we can re-enable OS sieve.
> Re-anable operating system sieve

- thoth/adviser/cli.py
Depends-On: https://github.com/thoth-station/analyzer/pull/186
> Add duration to Adviser

- openshift/buildConfig-template.yaml
- openshift/imageStream-template.yaml
- openshift/job-adviser-template.yaml
- openshift/job-dependencyMonkey-template.yaml
- openshift/job-provenanceChecker-template.yaml
updated templates with annotations and param thoth-advise-value
> updated templates with annotations and param thoth-advise-value

- openshift/buildConfig-template.yaml
Use THOTH_ADVISE variable for consistency
> Use THOTH_ADVISE variable for consistency

- thoth/adviser/cli.py
Reverts thoth-station/adviser#483
> Revert "runtime_environment var should be dict in parameter"

- setup.py
Fixes: https://github.com/thoth-station/adviser/issues/497
> Add missing modules

- thoth/adviser/resolver.py
It would be nice to notify user about computing recommendations when run
without debug mode so that user knows what's going on.
> Notify user when computing recommendations

- openshift/job-adviser-template.yaml
- openshift/job-dependencyMonkey-template.yaml
- openshift/job-provenanceChecker-template.yaml
Related: https://github.com/thoth-station/common/pull/549
> Propagate document id into jobs

- thoth/adviser/resolver.py
Method _do_run_steps is not used in codebase anymore.
> Remove unused method

- openshift/job-adviser-template.yaml
- openshift/job-provenanceChecker-template.yaml
Related: https://github.com/thoth-station/common/pull/578
> Do not show not relevant logs to users

- liveness.py
> Use SIGINT in liveness probe

- tests/predictors/test_annealing.py
- thoth/adviser/predictors/annealing.py
Fixes: https://github.com/thoth-station/adviser/issues/624
> Make temperature function a function of iteration as well

- openshift/workflow-adviser-template.yaml
this is an OpenShift Template to create an Argo Workflow to run an advise.
> added an Argo Workflow to run an advise

- tests/test_resolver.py
> Add tests for leaf node expansion with marker set to False

- openshift/job-adviser-template.yaml
> Exclude reports from run error in Sentry

- openshift/workflow-adviser-template.yaml
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   openshift/workflow-adviser-template.yaml
> Fixed adviser Workflow template

- openshift/workflow-adviser-template.yaml
Signed-off-by: Marek Cermak <macermak@redhat.com>
modified:   openshift/workflow-adviser-template.yaml
> Fixed missing emptyDir in the Adviser Workflow

- tests/boots/test_solved_software_environment.py
- tests/conftest.py
- tests/test_context.py
- tests/test_resolver.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/solved_software_environment.py
Depends-On: https://github.com/thoth-station/storages/pull/1443
> Introduce solved software environment boot

- openshift/workflow-adviser-template.yaml
> Adjust env variable name

- openshift/workflow-adviser-template.yaml
> Correct wrong key in template

- thoth/adviser/resolver.py
> Yield from generator to keep context

- openshift/job-dependencyMonkey-template.yaml
Related: https://github.com/thoth-station/common/pull/609
> Fix decision type environment variable name

- thoth/adviser/cli.py
- thoth/adviser/dependency_monkey.py
> Fix submitting inspections

- tests/test_resolver.py
- thoth/adviser/resolver.py
The state should be re-added if unresolved dependencies are still present.
> Fix bug shown when sieves or steps filtered out dependecies

- thoth/adviser/beam.py
Keep querying for top state in the beam in O(1). Perform top lookup in O(N)
only if top state has been removed. This optimizes predictors, such as
AdaptiveSimulatedAnnealing that ask for the top state but do not remove it each
time.
> Optimize handling of the top state kept in beam

- openshift/job-dependencyMonkey-template.yaml
> Assign correct default value

- openshift/job-adviser-template.yaml
Related: https://github.com/thoth-station/common/pull/623
> Use WARNING log level in thoth.common

- thoth/adviser/cli.py
instead of having __main__ logger.
> Ask for thoth.adviser log to have clean logs and respect log configuration

- openshift/job-adviser-template.yaml
- openshift/job-dependencyMonkey-template.yaml
- openshift/job-provenanceChecker-template.yaml
> Rename template for workflow-operator

- workflows/templates/finished-webhook-template.yaml
> Modify parameters for GitHub App

- openshift/adviser-template.yaml
- workflows/templates/advise-template.yaml
- workflows/templates/finished-webhook-template.yaml
> Use correct storage to store results

- tests/sieves/test_abi_compat.py
Add tests for new Adviser sieve #703
> abi-compat-sieve tests

- workflows/templates/advise-template.yaml
- workflows/templates/finished-webhook-template.yaml
> Add default value when user does not provided Pipfile.lock

- openshift/adviser-template.yaml
- workflows/templates/advise-template.yaml
- workflows/templates/finished-webhook-template.yaml
> Adjust version and use correct keys

- thoth/adviser/product.py
.. so that requires and other Pipfile metadata correctly show up in the
pipeline products.
> Propagate metadata to products

- openshift/job-dependencyMonkey-template.yaml
Fixes: https://github.com/thoth-station/adviser/issues/826
> Ignore the run logger for dependency monkey runs

- openshift/job-dependencyMonkey-template.yaml
Fixes: https://github.com/thoth-station/management-api/issues/399
> OpenShift templates are referenced by label

- Pipfile
- Pipfile.lock
See https://github.com/python/typeshed/issues/3001
> Remove typeshed

- .gitignore
- thoth/adviser/cli.py
- thoth/adviser/digests_fetcher.py
> Fixed error log and old api

- openshift/adviser-template.yaml
- workflows/templates/advise-template.yaml
Depends-On: https://github.com/thoth-station/workflows/pull/23
> Generalize variables for Ceph for the workflows

- workflows/templates/advise-template.yaml
> Adjust string for image and key

- thoth/adviser/exceptions.py
> Correct space for exception message

- openshift/adviser-template.yaml
- workflows/templates/advise-template.yaml
> Wrong variable name and missing variables

- workflows/templates/advise-template.yaml
> Missing parenthesis prevent sync on Ceph!!

- thoth/adviser/resolver.py
... this looks like better way of logging relative to the number of stacks produced (so logs are not too sparse or too versbose based on number of stacks to be generated)
> Log resolver progress each 10%

- docs/source/integration.rst
Related: https://github.com/thoth-station/s2i-thoth/pull/50
> Document provenance checks

- setup.py
- tests/sieves/test_abi_compat.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/abi_compat.py
* fix typo in class name
* define attributes used as slots
> Minor fixes in api_compat

- thoth/adviser/state.py
Based on https://medium.com/@fridex/optimizing-termial-random-by-removing-binomial-coefficient-e39b9ca7aaa3
> Optimize termial of n computation

- thoth/adviser/resolver.py
It can be directly returned as a pipeline product.
> Fix scoring of the user stack

- openshift/job-provenanceChecker-template.yaml
consistency in openshift templates to run provenance
> consistency in openshift templates to run provenance

- workflows/templates/advise-template.yaml
> Remove unusued parameter

- Pipfile
- Pipfile.lock
- requirements.txt
- thoth/adviser/beam.py
Depends-On: https://github.com/thoth-station/fext/pull/11 https://github.com/thoth-station/fext/pull/10
> Re-enable fext for beam's internal state handling

- thoth/adviser/resolver.py
This bug happens dependencies can have shared dependencies and resolution comes
to a state when not-yet resolved dependencies introduce a dependency already
resolved.
> Fix bug causing adviser halt for shared resolved packages

- tests/boots/test_python_version.py
- thoth/adviser/boots/python_version.py
... it can be misleading when requirements.txt are used
> Adjust the message produced

- openshift/adviser-template.yaml
- openshift/buildConfig-template.yaml
- openshift/imageStream-template.yaml
- openshift/job-adviser-template.yaml
- openshift/job-dependencyMonkey-template.yaml
- openshift/job-provenanceChecker-template.yaml
> fixed the apiVersion of all the OpenShift Templates

- Pipfile.lock
- tests/boots/test_platform.py
- tests/test_product.py
- tests/test_resolver.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/platform.py
- thoth/adviser/resolver.py
Depends-On: https://github.com/thoth-station/common/pull/777
> Implement platform boot

- thoth/adviser/resolver.py
> Improve message provided to user

- openshift/adviser-template.yaml
Related-to: https://github.com/thoth-station/adviser/issues/984
Depends-On: https://github.com/thoth-station/unresolved-package-handler/pull/18
> Add unsolved-package-handler to adviser workflow

- openshift/adviser-template.yaml
- workflows/templates/advise-template.yaml
- workflows/templates/finished-webhook-template.yaml
- workflows/templates/trigger-integration-template.yaml
Depends-On: https://github.com/thoth-station/workflow-helpers/pull/2
> create task trigger integration using workflow-helpers

- workflows/templates/trigger-integration-template.yaml
> correct typo

- .gitignore
- pyproject.toml
> Added pyproject.toml

- openshift/adviser-template.yaml
- workflows/templates/kebechet-run-results.yaml
As per discussion @KPostOffice
> :Removed unnecessary tempalates

- tests/boots/test_platform.py
- thoth/adviser/boots/platform.py
Depends-On: https://github.com/thoth-station/storages/pull/1801 https://github.com/thoth-station/storages/issues/1802
> Add a check for available platforms

- openshift/adviser-template.yaml
> Increase time for SLI

- openshift/adviser-template.yaml
> Remove dependency

- MANIFEST.in
> Adjust MANIFEST.in

- README.rst
> Add link to Provenance Checks

- docs/source/performance.rst
Related: https://github.com/thoth-station/performance/pull/49
> State aicoe and upstream specific build info for TensorFlow

- thoth/adviser/boots/python_version.py
- thoth/adviser/context.py
> Stack information is never None

- thoth/adviser/cli.py
- thoth/adviser/enums.py
https://github.com/thoth-station/adviser/pull/1058 https://github.com/thoth-station/adviser/issues/1053
> Rename to PERFORMANCE and SECURITY

- docs/source/unit.rst
> Document how to do unit placement in modules

- OWNERS
> Add Kevin to owners section

- thoth/adviser/cli.py
> Fix selecting dependency monkey predictor based on decision type

- tests/wraps/test_intel_tensorflow.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/intel_tensorflow.py
> Add a pipeline unit for suggesting Intel TensorFlow builds

- docs/source/developers_guide.rst
updated document with ceph deployment name specification
None
- Updated the developer document.
Updated the developer document with information on the thoth-deployment-name consistency.
> updated document with ceph deployment name specification

- docs/source/index.rst
- docs/source/introduction.rst
- docs/source/predictors/rl.rst
> Add docs for RL based predictors

- thoth/adviser/pipeline_builder.py
> Fix f-string expansion in exception

- thoth/adviser/run.py
> Fix handling of return code when using os.waitpid

- tests/steps/test_security_indicators.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/security_indicators.py
This step scores packages based on aggregated security info, all rewards are `> 0` but `< 1`
Closes: #1127
> add security indicator step

- tests/steps/test_security_indicators.py
- thoth/adviser/steps/security_indicators.py
> Fix performance recommendation name

- thoth/adviser/steps/security_indicators.py
As the same package can go through the pipeline multiple times, it can be nice to filter logged messages for users.
> Log warning about no SI just once per pipeline run

- thoth/adviser/cli.py
> Introduce a way to parametrize predictor

- tests/conftest.py
- tests/predictors/test_annealing.py
- tests/predictors/test_hill_climbing.py
- tests/predictors/test_latest.py
- tests/predictors/test_random_walk.py
- tests/predictors/test_sampling.py
> Fix warnings produced during executing the test suite

- tests/predictors/test_package_combinations.py
- thoth/adviser/predictors/__init__.py
- thoth/adviser/predictors/package_combinations.py
> Implement a predictor that generates package combinations

- docs/source/predictor.rst
> Document raising EagerStopPipeline in predictor

- tests/predictors/test_package_combinations.py
- tests/test_resolver.py
- thoth/adviser/predictors/__init__.py
- thoth/adviser/predictors/package_combinations.py
- thoth/adviser/resolver.py
- thoth/adviser/state.py
Depends-On: https://github.com/thoth-station/adviser/pull/1157
> Fix unresolved optimization

- tests/steps/test_tensorflow_21_urllib3.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/tensorflow_21_urllib3.py
Related: https://github.com/thoth-station/notebooks/issues/70
> Introduce a step prevents from resolving some combinations of urllib3 with TensorFlow=2.1

- thoth/adviser/run.py
- thoth/adviser/steps/aicoe.py
- thoth/adviser/steps/security_indicators.py
- thoth/adviser/steps/tensorflow_avx2.py
- thoth/adviser/wraps/intel_tensorflow.py
- thoth/adviser/wraps/mkl_threads.py
- thoth/adviser/wraps/no_onservation.py
- thoth/adviser/wraps/no_semantic_interposition.py
Related: https://github.com/thoth-station/common/pull/971
> Provide a link to justification to each pipeline unit

- thoth/adviser/run.py
- thoth/adviser/steps/aicoe.py
- thoth/adviser/steps/security_indicators.py
- thoth/adviser/steps/tensorflow_avx2.py
- thoth/adviser/wraps/intel_tensorflow.py
- thoth/adviser/wraps/mkl_threads.py
- thoth/adviser/wraps/no_onservation.py
- thoth/adviser/wraps/no_semantic_interposition.py
Reverts thoth-station/adviser#1177
> Revert "Provide a link to justification to each pipeline unit"

- tests/steps/test_security_indicators.py
- tests/steps/test_tensorflow_avx2.py
- tests/wraps/test_intel_tensorflow.py
- tests/wraps/test_mkl_threads.py
- tests/wraps/test_no_observation.py
- tests/wraps/test_no_semantic_interposition.py
- thoth/adviser/run.py
- thoth/adviser/steps/aicoe.py
- thoth/adviser/steps/security_indicators.py
- thoth/adviser/steps/tensorflow_avx2.py
- thoth/adviser/wraps/intel_tensorflow.py
- thoth/adviser/wraps/mkl_threads.py
- thoth/adviser/wraps/no_onservation.py
- thoth/adviser/wraps/no_semantic_interposition.py
> Provide a link to justification to pipeline units

- thoth/adviser/state.py
> Add an ability to specify manifest changes

- tests/steps/test_tf_22_prob.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/tf_22_prob.py
See https://github.com/tensorflow/tensorflow/issues/40584
> Restrict resolutions of tensorflow==2.2 with tensorflow-probability

- tests/steps/test_tf_22_prob.py
- thoth/adviser/steps/tensorflow_21_urllib3.py
- thoth/adviser/wraps/tf_accuracy.py
> Make pre-commit happy

- thoth/adviser/resolver.py
Related: https://github.com/thoth-station/thoth-station.github.io/pull/127
> Link to justification document when unresolved dependencies

- tests/steps/test_tf_22_prob.py
- thoth/adviser/steps/tf_22_prob.py
> Extend the tf-probability import error to all tensorflow-packages

- tests/test_product.py
- thoth/adviser/product.py
> State manifest changes in the pipeline product

- tests/wraps/test_tf_23_dict_bug.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/tf_23_dict_bug.py
See https://github.com/tensorflow/tensorflow/issues/42679
> Add a wrap that notifies about a bug in the summary output

- tests/test_state.py
- thoth/adviser/state.py
> Perform copy of the advised manifest changes on state clone

- Pipfile
- Pipfile.lock
- tests/wraps/test_mkl_threads.py
- thoth/adviser/state.py
- thoth/adviser/wraps/mkl_threads.py
Related: https://github.com/thoth-station/adviser/issues/1173
> Advise to add OMP_NUM_THREADS environment variable when MKL is used

- tests/steps/test_tensorflow_21_urllib3.py
- thoth/adviser/steps/tensorflow_21_urllib3.py
We can directly discard this resolution path as the stack produced does not work at all.
> Do not accept stacks with TF 2.1 and urllib3 that cause issues

- thoth/adviser/product.py
> Fix typing of advised manifest changes

- Pipfile
- Pipfile.lock
- tests/base.py
- tests/steps/tensorflow/test_tf_avx2.py
- tests/steps/test_aicoe.py
- tests/steps/test_cve.py
- tests/steps/test_security_indicators.py
Fixes: https://github.com/thoth-station/adviser/issues/963
> Provide mechanism to verify justification schema

- thoth/adviser/sieves/backports/enum34.py
- thoth/adviser/sieves/backports/functools32.py
- thoth/adviser/sieves/backports/importlib_metadata.py
- thoth/adviser/sieves/backports/importlib_resources.py
- thoth/adviser/sieves/backports/mock.py
> Use cached Python version tuples

- tests/base.py
- tests/conftest.py
- tests/test_beam.py
- tests/test_product.py
- tests/test_resolver.py
- tests/test_state.py
> Implement automatic schema checks in the testsuite

- tests/conftest.py
- tests/predictors/test_latest.py
- tests/test_product.py
- tests/test_resolver.py
- tests/test_state.py
> State is no longer using OrderedDict to gain performance

- tests/base.py
> Be more specific about justification types provided

- tests/conftest.py
> Rephrase code to make pydocstyle and black happy at the same time

- tests/conftest.py
- tests/test_state.py
> Fix the testsuite issue

- thoth/adviser/steps/tensorflow/tf_21_urllib3.py
- thoth/adviser/steps/tensorflow/tf_22_prob.py
- thoth/adviser/wraps/tensorflow/tf_23_accuracy.py
- thoth/adviser/wraps/tensorflow/tf_23_dict_bug.py
> Fix version checks - be accurate about TensorFlow versions

- setup.py
- tests/sieves/tensorflow/__init__.py
- tests/sieves/tensorflow/test_tf_cuda.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/tensorflow/__init__.py
- thoth/adviser/sieves/tensorflow/tf_cuda.py
> Recommend TensorFlow release based on CUDA present in environment

- tests/wraps/tensorflow/test_tf_intel.py
> Add test for intel TensorFlow

- thoth/adviser/predictors/latest.py
> Link justification for the approximating latest predictor

- thoth/adviser/boots/solved_software_environment.py
- thoth/adviser/resolver.py
- thoth/adviser/run.py
- thoth/adviser/sieves/backports/enum34.py
- thoth/adviser/sieves/backports/functools32.py
- thoth/adviser/sieves/backports/importlib_metadata.py
- thoth/adviser/sieves/backports/importlib_resources.py
- thoth/adviser/sieves/backports/mock.py
- thoth/adviser/steps/cve.py
To give more context to the users.
> Provide justification links to various parts of the resolution process

- thoth/adviser/resolver.py
> Link justification documents related to resolver messages

- tests/steps/tensorflow/test_tf_113_numpy.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/tensorflow/__init__.py
- thoth/adviser/steps/tensorflow/tf_113_numpy.py
See https://github.com/tensorflow/tensorflow/issues/25636
> Add a step to tp correct version of NumPy with TF==1.13.1

- thoth/adviser/predictors/latest.py
> Fix wrong import

- thoth/adviser/unit.py
> Turn warnings into errors reported when AICoE index cannot be parsed

- thoth/adviser/steps/cve.py
> Fix providing justification to CVE step

- thoth/adviser/resolver.py
- thoth/adviser/run.py
> Fix message printed

- thoth/adviser/sieves/backports/enum34.py
- thoth/adviser/sieves/backports/functools32.py
- thoth/adviser/sieves/backports/mock.py
> Fix formatting in backports

- thoth/adviser/resolver.py
> Add justification links related to user stack scoring

- thoth/adviser/run.py
> Fix pre-commit issues reported

- tests/steps/test_cve.py
- thoth/adviser/steps/cve.py
> Do not accept CVEs when recommendation type is set to security

- tests/steps/tensorflow/test_tf_22_numpy.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/tensorflow/__init__.py
- thoth/adviser/steps/tensorflow/tf_22_numpy.py
https://github.com/numpy/numpy/pull/15355
https://github.com/tensorflow/tensorflow/commit/79518facb4b857af9d9d5df2da463fdbf7eb0e3e
https://github.com/tensorflow/tensorflow/issues/41902
> Do not recommend using TensorFlow<2.3>=2.0 with NumPy>=1.19.0

- tests/steps/tensorflow/test_tf_114_gast.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/tensorflow/__init__.py
- thoth/adviser/steps/tensorflow/tf_114_gast.py
https://github.com/tensorflow/tensorflow/pull/32989
https://github.com/tensorflow/tensorflow/issues/32319
> A pipeline step to prevent resolving TF<=1.14 with gast>0.2.2

- tests/boots/test_python_version.py
- thoth/adviser/boots/python_version.py
https://github.com/thoth-station/thoth-station.github.io/pull/167
> Add a link to Python version justification

- docs/source/sieves.rst
- docs/source/steps.rst
- tests/test_resolver.py
- thoth/adviser/resolver.py
> Add a mechanism to skip packages from a stack based on pipeline steps

- tests/test_state.py
- tests/wraps/tensorflow/test_tf_mkl_threads.py
- thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
> Notify about proper usage of Intel's MKL

- tests/boots/test_ubi.py
- thoth/adviser/boots/platform.py
- thoth/adviser/boots/python_version.py
- thoth/adviser/boots/rhel_version.py
- thoth/adviser/boots/solved_software_environment.py
- thoth/adviser/boots/ubi.py
> Add stack information in boots

- tests/sieves/test_prereleases.py
- thoth/adviser/sieves/prereleases.py
> Include pre-releases pipeline unit only if pre-releases are disabled

- tests/steps/tensorflow/test_tf_113_numpy.py
- tests/steps/tensorflow/test_tf_21_urllib3.py
- tests/steps/tensorflow/test_tf_22_prob.py
- thoth/adviser/steps/tensorflow/tf_113_numpy.py
- thoth/adviser/steps/tensorflow/tf_114_gast.py
- thoth/adviser/steps/tensorflow/tf_21_urllib3.py
- thoth/adviser/steps/tensorflow/tf_22_numpy.py
- thoth/adviser/steps/tensorflow/tf_22_prob.py
- thoth/adviser/steps/tensorflow/tf_rm_scipy.py
> Provide stack info in step pipeline units

- tests/sieves/pandas/test_py36_drop.py
- tests/sieves/setuptools/test_py36.py
- tests/sieves/test_solved.py
- thoth/adviser/boots/platform.py
- thoth/adviser/boots/solved_software_environment.py
- thoth/adviser/sieves/abi_compat.py
- thoth/adviser/sieves/pandas/py36_drop.py
- thoth/adviser/sieves/setuptools/py36.py
- thoth/adviser/sieves/solved.py
- thoth/adviser/sieves/tensorflow/tf_cuda.py
> Provide stack info in pipeline sieves

- tests/sieves/pandas/test_py36_drop.py
- thoth/adviser/sieves/pandas/__init__.py
- thoth/adviser/sieves/pandas/py36_drop.py
> Rename sieve to conform naming convention

- thoth/adviser/sieves/__init__.py
> Fix master branch

- thoth/adviser/steps/tensorflow/tf_113_numpy.py
- thoth/adviser/steps/tensorflow/tf_114_gast.py
- thoth/adviser/steps/tensorflow/tf_21_urllib3.py
- thoth/adviser/steps/tensorflow/tf_22_numpy.py
- thoth/adviser/steps/tensorflow/tf_22_prob.py
- thoth/adviser/steps/tensorflow/tf_rm_scipy.py
> Fix black complains

- docs/source/index.rst
- docs/source/pseudonyms.rst
- setup.py
- tests/base.py
- tests/conftest.py
- tests/helpers.py
- tests/pseudonyms/__init__.py
- tests/pseudonyms/test_intel_tensorflow.py
- tests/pseudonyms/test_intel_tensorflow_cpu.py
- tests/pseudonyms/test_tensorflow_gpu.py
- tests/test_pipeline_builder.py
- tests/test_pipeline_config.py
- tests/test_report.py
- tests/test_resolver.py
- tests/units/pseudonyms.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/pipeline_config.py
- thoth/adviser/pseudonym.py
- thoth/adviser/pseudonyms/__init__.py
- thoth/adviser/pseudonyms/intel_tensorflow.py
- thoth/adviser/pseudonyms/intel_tensorflow_cpu.py
- thoth/adviser/pseudonyms/tensorflow_gpu.py
- thoth/adviser/resolver.py
> Introduce Pseudonym pipeline unit type

- tests/test_resolver.py
- tests/units/pseudonyms.py
- thoth/adviser/resolver.py
> Pseudonyms testsuite

- tests/base.py
- tests/conftest.py
- tests/pseudonyms/test_intel_tensorflow.py
- tests/pseudonyms/test_tensorflow_gpu.py
- tests/test_pipeline_builder.py
- tests/test_pipeline_config.py
- tests/units/pseudonyms.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/pseudonym.py
- thoth/adviser/pseudonyms/intel_tensorflow.py
- thoth/adviser/pseudonyms/intel_tensorflow_cpu.py
- thoth/adviser/pseudonyms/tensorflow_gpu.py
> Pass package_name from unit configuration

- tests/test_resolver.py
> Add tests related to unit_run flag

- thoth/adviser/steps/cve.py
> Add missing schema

- tests/test_resolver.py
- thoth/adviser/resolver.py
> Add tests for skipping a package from steps

- setup.py
> Use find_namespace_packages to discover all thoth-adviser modules

- MANIFEST.in
- README.rst
> Adjust README file

- Pipfile
- Pipfile.lock
Related: https://github.com/thoth-station/kebechet/pull/575/ https://github.com/thoth-station/kebechet/issues/574
> Remove voluptuous from dev-packages it is already in packages

- thoth/adviser/step.py
> Fix docstring

- docs/source/compatibility.rst
> Adjust compatibility section in docs

- docs/source/integration.rst
> Fix urls in the integration section

- docs/source/unit.rst
- thoth/adviser/pseudonym.py
- thoth/adviser/sieve.py
- thoth/adviser/step.py
- thoth/adviser/unit.py
> Some units are specific to package, not to package version

- docs/source/justifications.rst
> Fix trailing white space

- tests/conftest.py
- tests/strides/test_one_version.py
- tests/test_pipeline_builder.py
- tests/test_pipeline_config.py
- tests/test_report.py
- tests/test_resolver.py
- tests/units/boots.py
- tests/units/strides.py
- tests/units/wraps.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/pipeline_config.py
- thoth/adviser/pseudonym.py
- thoth/adviser/resolver.py
- thoth/adviser/sieve.py
- thoth/adviser/step.py
- thoth/adviser/strides/one_version.py
- thoth/adviser/unit.py
> Implement package version in configuration for boots, strides and wraps

- tests/test_pipeline_builder.py
- thoth/adviser/pipeline_builder.py
> Introduce capability for obtaining units inside a builder context

- tests/base.py
- tests/strides/test_one_version.py
> Test default configuration schema in units

- thoth/adviser/resolver.py
> Remove unused exception

- thoth/adviser/pipeline_builder.py
... when passing pipeline config as a config file
> Allow null values in pipeline units listing

- thoth/adviser/steps/_debug/mock_score.py
> Provide probability configuration for assigning a score

- thoth/adviser/pipeline_builder.py
> Units do not need to be stated in the configuration

- tests/predictors/test_td.py
- thoth/adviser/predictors/td.py
- thoth/adviser/steps/_debug/set_score.py
> Implement n-step TD learning

- thoth/adviser/beam.py
> Clear beam history

- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/_debug/__init__.py
> Register debug units so they can be easily run using supplied conf

- thoth/adviser/steps/_debug/set_score.py
> Set score can now generate random score if not explicitly provided

- thoth/adviser/steps/_debug/set_score.py
> Allow assigning score when package version or index url is not set

- thoth/adviser/resolver.py
> Deinstantiate solver and let gc do its job

- thoth/adviser/dependency_monkey.py
- thoth/adviser/resolver.py
- thoth/adviser/run.py
> Plot resolver history

- thoth/adviser/resolver.py
> Be more accurate with plot label

- thoth/adviser/resolver.py
> Fix message logged

- thoth/adviser/predictors/annealing.py
> Make temperature coefficient parametrize and increase it

- thoth/adviser/predictors/annealing.py
- thoth/adviser/predictors/td.py
> Fix n-step TD-learning

- thoth/adviser/steps/_debug/mock_score.py
- thoth/adviser/steps/_debug/set_score.py
... and use constants for MAX/MIN.
> Turn off multi package resolution for debug units

- thoth/adviser/steps/_debug/generate_score.py
> Enable probability assigning score when generating scores

- thoth/adviser/steps/_debug/mock_score.py
> Fix assigning score based on probability

- thoth/adviser/resolver.py
> Log the highest rated software stack found so far

- thoth/adviser/resolver.py
> Log based on iteration not based on final states produced

- thoth/adviser/resolver.py
> Add more weak condition when logging progress

- thoth/adviser/resolver.py
> Remove unused parts

- thoth/adviser/beam.py
- thoth/adviser/resolver.py
> Adjust plot labels

- thoth/adviser/predictors/mcts.py
> Fix MCTS history keeping

- thoth/adviser/predictors/td.py
> Introduce trace parameter to TD learning

- thoth/adviser/cli.py
- thoth/adviser/predictor.py
> Switch to TD-learning with step==2 instead of Monte Carlo learning

- thoth/adviser/cli.py
> Do one step TD-learning and turn off trace

- tests/test_predictor.py
- thoth/adviser/utils.py
> Do not keep history by default

- tests/predictors/test_td.py
- thoth/adviser/predictors/td.py
Once the temperature drops, perform just eploitation, no need to have additional overhead.
> Temperature computation and probability does not need to be done for t=0

- thoth/adviser/resolver.py
> Print found stack score to logs

- thoth/adviser/predictors/td.py
> Fix history kept in TD-learning

- thoth/adviser/boots/version_clash.py
- thoth/adviser/exceptions.py
- thoth/adviser/predictors/td.py
- thoth/adviser/resolver.py
> Add stack info when no stack is produced

- thoth/adviser/resolver.py
> Improve message logged

- thoth/adviser/resolver.py
> Provide stack info if direct dependencies were not resolved

- thoth/adviser/resolver.py
> Point to the existing relevant justification document

- thoth/adviser/exceptions.py
- thoth/adviser/resolver.py
> Provide stack info if resolver failed to resolve direct dependencies

- docs/source/predictors/neural_network.rst
> Add documentation for predictor that uses a gradient based method

- docs/source/index.rst
- docs/source/manifest_changes.rst
- thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
> Add docs for advising manifest changes

- docs/source/manifest_changes.rst
> Fix manifest changes docs

- docs/source/predictors/neural_network.rst
> Fix pre-commit complains

- tests/test_resolver.py
> Fix adviser testsuite

- docs/source/steps.rst
- tests/base.py
- tests/steps/test_dropout.py
- tests/test_pipeline_builder.py
- tests/test_pipeline_config.py
- tests/test_resolver.py
- tests/test_step.py
- tests/units/steps.py
- thoth/adviser/resolver.py
- thoth/adviser/step.py
- thoth/adviser/steps/_debug/generate_score.py
- thoth/adviser/steps/_debug/mock_score.py
- thoth/adviser/steps/_debug/set_score.py
- thoth/adviser/steps/aicoe.py
- thoth/adviser/steps/cve.py
- thoth/adviser/steps/dropout.py
- thoth/adviser/steps/security_indicators.py
- thoth/adviser/steps/tensorflow/tf_113_numpy.py
- thoth/adviser/steps/tensorflow/tf_114_gast.py
- thoth/adviser/steps/tensorflow/tf_21_urllib3.py
- thoth/adviser/steps/tensorflow/tf_22_numpy.py
- thoth/adviser/steps/tensorflow/tf_22_prob.py
- thoth/adviser/steps/tensorflow/tf_avx2.py
- thoth/adviser/steps/tensorflow/tf_rm_scipy.py
> Make multi_package_resolution part of the step unit configuration

- docs/source/integration.rst
Closes - https://github.com/thoth-station/kebechet/issues/461
Related - https://github.com/thoth-station/kebechet/issues/576
> Added documentation to integrate kebechet

- docs/source/index.rst
- docs/source/predictors/package_combinations.rst
> Add docs for package combinations predictor

- docs/source/predictors/package_combinations.rst
> Fix trailing whitespace in docs

- thoth/adviser/resolver.py
> Log message only if relevant

- docs/source/integration.rst
> Minor formatting changes in Kebechet docs

- tests/test_report.py
- thoth/adviser/report.py
- thoth/adviser/resolver.py
> Propagate statistics to the final report

- tests/pseudonyms/_debug/__init__.py
- tests/pseudonyms/_debug/test_alias.py
- thoth/adviser/pseudonyms/_debug/__init__.py
- thoth/adviser/pseudonyms/_debug/alias.py
> Add a generic alias pseudonym unit

- thoth/adviser/run.py
... by the parent process on an error
Fixes: #1478
> Handle cannot produce stack exception so results are not overwritten

- tests/steps/tensorflow/test_tf_21_h5py.py
- thoth/adviser/steps/__init__.py
- thoth/adviser/steps/tensorflow/__init__.py
- thoth/adviser/steps/tensorflow/tf_21_h5py.py
Fixes: https://github.com/thoth-station/adviser/issues/1519
> A pipeline unit that suggests not to use h5py>=3 with TF==2.1

- tests/sieves/tensorflow/test_tf_py39.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/tensorflow/__init__.py
- thoth/adviser/sieves/tensorflow/tf_py39.py
Fixes: #1520
Related: https://github.com/thoth-station/adviser/issues/1520
Related: https://github.com/tensorflow/tensorflow/issues/44485
> Introduce a sieve for filtering out incompatible TensorFlow for Py3.9

- liveness.py
- thoth/adviser/predictors/td.py
Fixes: https://github.com/thoth-station/adviser/issues/1526
> Handle SIGUSR1 handler to stop exploitation phase

- thoth/adviser/beam.py
> Add a temporary workaround for #1541

- thoth/adviser/dependency_monkey.py
> Increase verbosity to see where inspections are triggered

- tests/steps/test_security_indicators.py
- thoth/adviser/steps/security_indicators.py
> Provide stack info in security indicators

- thoth/adviser/resolver.py
> Add missing link to user-stack scoring justification

- tests/wraps/tensorflow/test_tf_38518.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/tensorflow/__init__.py
- thoth/adviser/wraps/tensorflow/tf_38518.py
Related: https://github.com/tensorflow/tensorflow/issues/38518
Fixes: https://github.com/thoth-station/adviser/issues/1555
> Add a wrap that notifies about a bug when mutliple instances of TF are running

- tests/wraps/tensorflow/test_tf_42475.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/tensorflow/__init__.py
- thoth/adviser/wraps/tensorflow/tf_42475.py
Related: https://github.com/tensorflow/tensorflow/issues/42475
Fixes: https://github.com/thoth-station/adviser/issues/1557
> Add a pipeline unit wrap for slow keras embedding layer

- tests/wraps/tensorflow/test_tf_42475.py
- thoth/adviser/wraps/tensorflow/tf_42475.py
Related: https://github.com/thoth-station/adviser/pull/1558#issuecomment-726352828
> Consider library usage for TF 42475 wrap

- Pipfile.lock
- tests/boots/test_python_version.py
- thoth/adviser/boots/python_version.py
> Report warning if Python versions do not match

- thoth/adviser/resolver.py
> Match score of the user's stack printed with the final score reported

- tests/steps/test_security_indicators.py
- thoth/adviser/steps/security_indicators.py
Related: https://github.com/thoth-station/storages/pull/2069
> Handle exception raised when the given record was not found

- thoth/adviser/resolver.py
> Improve message logged when reporting resolver's progress

- docs/source/manifest_changes.rst
- tests/test_product.py
- tests/wraps/tensorflow/test_mkl_threads.py
- tests/wraps/tensorflow/test_tf_mkl_threads.py
- thoth/adviser/state.py
- thoth/adviser/wraps/tensorflow/tf_mkl_threads.py
Fixes: #1582 
properly JSON formatted advised manifest changes
> properly JSON formatted advised manifest changes

- tests/test_product.py
- thoth/adviser/product.py
> Include dependency if at least one lib always requires it

- docs/source/integration.rst
Related: https://github.com/thoth-station/thamos/pull/632
> Introduce THOTH_CONFIG_CHECK environment variable

- docs/source/integration.rst
Updated kebechet marketplace app link. 
Related - https://github.com/thoth-station/kebechet/issues/608
> Updated marketplace app link

- tests/predictors/test_td.py
- tests/wraps/tensorflow/test_mkl_threads.py
- tests/wraps/tensorflow/test_tf_mkl_threads.py
> Fix testsuite for Python 3.8

- tests/sieves/tensorflow/test_tf_cuda.py
- thoth/adviser/sieves/tensorflow/tf_cuda.py
See: https://github.com/tensorflow/tensorflow/issues/45308
> Recommend TensorFlow 2.4 based on CUDA support

- docs/source/compatibility.rst
> State python_requires in the compatibility section of docs

- docs/source/integration.rst
> docs: State build-watcher in the integration section

- tests/wraps/test_thoth_s2i.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/thoth_s2i.py
Fixes: https://github.com/thoth-station/adviser/issues/1634
> Add a pipeline unit recommending Thoth's s2i as a base

- tests/boots/test_gpu.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/gpu.py
Fixes: https://github.com/thoth-station/adviser/issues/1628
Related: https://github.com/thoth-station/thamos/issues/707
> Implement a pipeline unit which checks GPU and CUDA supplied

- tests/wraps/test_thoth_s2i_info.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/thoth_s2i_info.py
Adds a pipeline unit that links to a page with Thoth s2i information used.
> Add a wrap that adds information about Thoth s2i used

- tests/test_product.py
> Fix tests related to Thoth's common config changes

- docs/source/index.rst
> Link Experimental features section from docs index

- .s2i/bin/run
- MANIFEST.in
- prepare.py
Related: https://github.com/thoth-station/thoth-application/issues/902
> Prepare inputs for adviser container run

- thoth/adviser/cli.py
> Show used library usage in the resulting JSON report

- prepare.py
> No need to sort JSON keys when preparing inputs

- docs/source/experimental_features.rst
Depends-On: https://github.com/thoth-station/python/pull/349
Depends-On: https://github.com/thoth-station/adviser/pull/1668
> Document strict index configuration feature

- tests/sieves/test_experimental_conf_index.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/experimental_filter_conf_index.py
Related: https://github.com/thoth-station/adviser/pull/1680/
Depends-On: https://github.com/thoth-station/python/pull/349/
> Introduce a sieve for filtering packages not coming from an index

- prepare.py
> Remove sleep part from the prepare script used for debugging

- thoth/adviser/cli.py
Fixes: https://github.com/thoth-station/adviser/issues/1697
> Fix issues caused when Pipfile.lock is set to null by prepare.py

- thoth/adviser/sieves/__init__.py
> Remove parts introduced by wrong rebase

- setup.py
> Increase timeout for a test case

- thoth/adviser/cli.py
> Propagate parsed Dependency Monkey inputs to the resulting JSON output

- prepare.py
> Remove bits related to preparation

- tests/test_product.py
> Fixes related to thoth-common adjustments

- thoth/adviser/solver.py
> Fix when package version is any version

- tests/sieves/test_experimental_conf_index.py
- thoth/adviser/sieves/experimental_filter_conf_index.py
> Add justification for index configuration filter

- tests/sieves/test_experimental_prereleases.py
- thoth/adviser/sieves/experimental_prereleases.py
> Provide justification when filtering based on selective pre-releases

- tests/sieves/test_experimental_package_index.py
- thoth/adviser/sieves/experimental_package_index.py
> Add justification for filtering packages based on index configuration

- tests/boots/test_pipfile_hash.py
- thoth/adviser/boots/pipfile_hash.py
Related: https://github.com/thoth-station/adviser/issues/1724
> Remove user's stack if any changes in requirements were detected

- Pipfile.lock
> Manual dependency update

- tests/test_product.py
- tests/test_report.py
- thoth/adviser/product.py
Fixes: https://github.com/thoth-station/thamos/issues/785
> Fix missing thoth section in the recommended stack

- tests/sieves/backports/test_enum34.py
- tests/sieves/backports/test_functools32.py
- tests/sieves/backports/test_importlib_metadata.py
- tests/sieves/backports/test_importlib_resources.py
- tests/sieves/backports/test_mock.py
- thoth/adviser/sieves/backports/enum34.py
- thoth/adviser/sieves/backports/functools32.py
- thoth/adviser/sieves/backports/importlib_metadata.py
- thoth/adviser/sieves/backports/importlib_resources.py
- thoth/adviser/sieves/backports/mock.py
> Fix justification messages reported by backport sieves

- thoth/adviser/wraps/thoth_s2i_info.py
> Fix link to Thoth s2i info

- thoth/adviser/wraps/thoth_s2i_info.py
> Adjust type of the message for S2I info

- tests/test_product.py
- tests/test_report.py
- thoth/adviser/product.py
- thoth/adviser/report.py
> Propagate metadata to justification and stack info

- docs/source/index.rst
- docs/source/prescription.rst
- tests/test_pipeline_builder.py
- tests/test_resolver.py
- thoth/adviser/cli.py
- thoth/adviser/exceptions.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/pipeline_config.py
- thoth/adviser/prescription/__init__.py
- thoth/adviser/prescription/prescription.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/boot.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/pseudonym.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/stride.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/prescription/v1/wrap.py
- thoth/adviser/pseudonym.py
- thoth/adviser/resolver.py
- thoth/adviser/sieve.py
- thoth/adviser/step.py
- thoth/adviser/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/1735
With this change, Thoth operators will be able to supply prescriptions for the resolver. Prescription is a declarative way to configure resolver's behavior.
> Introduce prescription

- tests/test_resolver.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/prescription/v1/boot.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/pseudonym.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/resolver.py
- thoth/adviser/unit_types.py
> Fix typing for prescription units and core units

- thoth/adviser/cli.py
> Provide a sub-command to validate prescription YAML

- docs/source/prescription.rst
> Add a note to prescription docs

- thoth/adviser/pipeline_builder.py
- thoth/adviser/prescription/v1/prescription.py
> Improve type handling in the prescription module

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/prescription/v1/wrap.py
> Add extend justification links if links do not point to any hosted site

- thoth/adviser/prescription/v1/unit.py
> Add URL to logged message automatically

- tests/boots/test_ubi.py
- thoth/adviser/boots/ubi.py
> Register UBI boot only if UBI is used

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/sieves/experimental_package_index.py
> State logged message rather than logged text

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/schema.py
> Add release and data infor to the prescription chema

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
> Prescription listing

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
> Allow multiple hardware configurations per pipeline unit

- docs/source/prescription.rst
- tests/prescription/__init__.py
- tests/prescription/v1/__init__.py
- tests/prescription/v1/base.py
- tests/prescription/v1/test_boot.py
- tests/prescription/v1/test_prescription.py
- tests/prescription/v1/test_pseudonym.py
- tests/prescription/v1/test_sieve.py
- tests/prescription/v1/test_step.py
- tests/prescription/v1/test_stride.py
- tests/prescription/v1/test_unit.py
- tests/prescription/v1/test_wrap.py
- tests/test_pipeline_builder.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/prescription/v1/boot.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/pseudonym.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/stride.py
- thoth/adviser/prescription/v1/unit.py
> Test prescription units

- thoth/adviser/cli.py
- thoth/adviser/exceptions.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
> Allow multiple prescription files being supplied to the resolver

- thoth/adviser/prescription/v1/schema.py
> Fix checking justification link

- docs/source/prescription.rst
- tests/data/prescriptions/basic.yaml
- tests/prescription/v1/test_prescription.py
- tests/test_pipeline_builder.py
- thoth/adviser/prescription/v1/prescription.py
> Test loading prescriptions

- tests/boots/test_prescription_release.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/prescription_release.py
- thoth/adviser/context.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/resolver.py
> Add a pipeline unit that notifies about prescription release used

- docs/source/prescription.rst
- tests/prescription/v1/test_pseudonym.py
- thoth/adviser/prescription/v1/pseudonym.py
- thoth/adviser/prescription/v1/schema.py
> Add ability to yield matched package version in pseudonyms

- docs/source/prescription.rst
> Adjust pseudonym example with yield matched version

- tests/boots/test_prescription_release.py
- tests/data/prescriptions/basic.yaml
- tests/prescription/v1/test_prescription.py
- thoth/adviser/boots/prescription_release.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
With this change, prescriptions will be available in namespace per prescription file. It will reduce possible clashes when multiple prescription files are used.
> Introduce namespace for prescriptions

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
... also adjust schema and prescription schema validation env variable name.
> Remove wisdom from the prescription yaml

- docs/source/justifications.rst
- docs/source/prescription.rst
> Update prescription documentation so users can start using it

- thoth/adviser/wraps/tensorflow/tf_42475.py
> Use package name from configuration to reduce some hashing

- thoth/adviser/wraps/no_onservation.py
> Be more positive with justification message reported

- tests/boots/test_thoth_s2i.py
- tests/boots/test_thoth_s2i_info.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/thoth_s2i.py
- thoth/adviser/boots/thoth_s2i_info.py
- thoth/adviser/wraps/__init__.py
> Rewrite s2i wraps to boots to match semantics

- thoth/adviser/steps/security_indicators.py
Change how SI is scored and also add positive justification when possible
> change si scoring and add info justification

- docs/source/prescription.rst
> Fix step example in prescriptions

- tests/steps/test_security_indicators.py
- thoth/adviser/steps/security_indicators.py
> Adjustments in security indicators

- thoth/adviser/pipeline_builder.py
> Register core units first before any prescriptions

- docs/source/prescription.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
> Allow supplying expected library usage in prescriptions

- docs/source/prescription.rst
- tests/prescription/v1/test_wrap.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/wrap.py
> Add ability to declare advised manifest changes in wrap prescriptions

- docs/source/prescription.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
> Add "not" operator to the prescription declaration

- thoth/adviser/pipeline_builder.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/unit.py
- thoth/adviser/wraps/__init__.py
> Fix handling prescription unit names

- thoth/adviser/report.py
- thoth/adviser/resolver.py
> Fix handling optimized wrap call based on product score

- docs/source/developers_guide.rst
- docs/source/prescription.rst
- tests/data/prescriptions/basic.yaml
- tests/prescription/v1/test_boot.py
- tests/prescription/v1/test_pseudonym.py
- tests/prescription/v1/test_sieve.py
- tests/prescription/v1/test_step.py
- tests/prescription/v1/test_stride.py
- tests/prescription/v1/test_wrap.py
- thoth/adviser/prescription/v1/boot.py
- thoth/adviser/prescription/v1/pseudonym.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/stride.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/prescription/v1/wrap.py
- thoth/adviser/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/1804
> Allow including one pipeline unit multiple times per matched entry

- thoth/adviser/prescription/v1/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/1808
> Remove not relevant to do comment

- docs/source/boots.rst
- docs/source/compatibility.rst
- docs/source/deployment.rst
- docs/source/developers_guide.rst
- docs/source/experimental_features.rst
- docs/source/index.rst
- docs/source/integration.rst
- docs/source/introduction.rst
- docs/source/pipeline.rst
- docs/source/predictors/reinforcement_learning.rst
- docs/source/prescription.rst
- docs/source/resolver.rst
- docs/source/sieves.rst
- docs/source/unit.rst
> Minor improvements in docs

- docs/source/prescription.rst
- tests/prescription/v1/test_github_release_notes.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/github_release_notes.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
> Add github release notes to justification

- thoth/adviser/resolver.py
Fixes: #1822 
Adjust format of the reported error to match with other reports.
> Adjust format for unsolved direct dependencies report

- docs/source/prescription.rst
Related: https://github.com/thoth-station/adviser/pull/1821
Related: https://github.com/thoth-station/prescriptions/pull/17
> Link YouTube video and pull request implementing GH release notes wrap

- MANIFEST.in
- prepare.py
- tests/data/constraints/constraints_0.txt
- tests/sieves/test_constraints.py
- tests/test_pipeline_builder.py
- tests/test_product.py
- thoth/adviser/cli.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/constraints.py
Closes: https://github.com/thoth-station/thoth-application/issues/1182
> Implement support for constraints

- docs/source/experimental_features.rst
Related: https://github.com/thoth-station/core/issues/271
> Document how to use constraints files

- docs/source/prescription.rst
- tests/prescription/v1/test_skip_package.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/skip_package.py
Fixes: https://github.com/thoth-station/adviser/issues/1843
> Add support for skip package prescription unit

- thoth/adviser/sieves/legacy_version.py
The resolution log can be bloated when legacy versions are found.
> Log removal of a legacy version just once

- thoth/adviser/resolver.py
> Report all unresolved dependencies

- tests/boots/test_fully_specified_environment.py
- thoth/adviser/boots/fully_specified_environment.py
- thoth/adviser/boots/solved_software_environment.py
- thoth/adviser/resolver.py
Fixes: https://github.com/thoth-station/adviser/issues/1855
Related: https://github.com/thoth-station/thoth-station.github.io/pull/207
> Make boot pipeline unit responsible for providing stack info

- tests/test_resolver.py
- thoth/adviser/resolver.py
> Handle error when all the direct deps are sieved

- docs/source/experimental_features.rst
Related: https://github.com/thoth-station/core/issues/271
> Add video demonstrating constaints.txt use

- docs/source/architecture.rst
- docs/source/deployment.rst
- docs/source/developers_guide.rst
- docs/source/pipeline.rst
- docs/source/predictors/annealing.rst
- docs/source/predictors/latest.rst
Fixed issues with broken links, typos  and styling.
…
… Explain your changes.
> Updates to website

- docs/source/deployment.rst
Related: https://github.com/thoth-station/thoth-application/issues/1403
> Document solver rules

- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/rules.py
Related: https://github.com/thoth-station/thoth-application/issues/1403
Depends-On: https://github.com/thoth-station/storages/pull/2321
> Add a sieve implementing filtering based on solver rules

- tests/steps/test_cve.py
- thoth/adviser/steps/cve.py
Related: https://github.com/thoth-station/cve-update-job/issues/404
Related: https://github.com/thoth-station/cve-update-job/pull/405
Depends-On: https://github.com/thoth-station/storages/pull/2320
> Adjust for CVEs consumed from PyPA

- tests/steps/test_cve.py
- thoth/adviser/steps/cve.py
> Keep CVE advisory in the justification output

- tests/test_rules.py
> Add tests for solver rules

- tests/boots/test_labels.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/labels.py
Related: https://github.com/thoth-station/adviser/issues/1885
> Notify users about labels used during the resolution process

- thoth/adviser/cli.py
Fixes: https://github.com/thoth-station/adviser/issues/1897
> Fix wrong read variable

- Pipfile
- Pipfile.lock
- tests/boots/test_solvers_configured.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/solvers_configured.py
Related: https://github.com/thoth-station/thoth-application/pull/1631
Related: https://github.com/thoth-station/thoth-application/issues/1516
> Notify users if they use runtime environment not known to deployment

- thoth/adviser/cli.py
- thoth/adviser/prescription/v1/prescription.py
> Adjust validate logic to consume prescriptions from a dir

- docs/source/prescription.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/exceptions.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/sieves/thoth_s2i_abi_compat.py
- thoth/adviser/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/1925
> Filter Python packages present in software stack based on so files

- docs/source/prescription.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/1922
> Perform recommendations based on RPM packages present in the environment

- docs/source/security.rst
Closes: thoth-station/si-cloc#26
> add docs for security advises

- docs/source/architecture.rst
Related: https://github.com/thoth-station/pulp-repository-sync-job/pull/3
Related: https://github.com/thoth-station/thoth-application/issues/1733
> docs: Add pulp-python monitoring job

- docs/source/index.rst
> Point users to support repository to report issues

- tests/base.py
- tests/sieves/test_thoth_s2i_packages.py
- thoth/adviser/exceptions.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/thoth_s2i_packages.py
Fixes: https://github.com/thoth-station/adviser/issues/1948
> Implement a pipeline unit for filtering Python packages already present in the base

- thoth/adviser/sieves/solved.py
Fixes: https://github.com/thoth-station/adviser/issues/1983
> Rename build time error to installation time error

- thoth/adviser/prescription/v1/unit.py
> Decrease log level accidentally stated as error

- Pipfile
- Pipfile.lock
> Pin flexmock to <=0.10.4

- tests/wraps/test_pulp_release.py
- thoth/adviser/wraps/pulp_release.py
> Add package name to Pulp information

- tests/wraps/test_sort_justifications.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/sort_justifications.py
> Sort resulting justification for better UX

- tests/wraps/test_libraries_io.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/libraries_io.py
> Link package information to libraries.io

- tests/wraps/test_pypi_release.py
- thoth/adviser/wraps/pypi_release.py
> Add package name to PyPI release justification info

- tests/test_product.py
- tests/test_report.py
- thoth/adviser/product.py
Fixes: https://github.com/thoth-station/adviser/issues/1978
Fixes: https://github.com/thoth-station/user-api/issues/1471
> State dependency graph in the resulting document

- tests/wraps/test_pulp_release.py
- thoth/adviser/wraps/pulp_release.py
> Make Pulp URL configurable

- thoth/adviser/prescription/v1/schema.py
> Improve parsing of Python package name and extend justification

- docs/source/prescription.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
ABI should be more appropriate.
> Rename shared objects to ABI

- docs/source/prescription.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/prescription/v1/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/2008
> Implement "globbing" when including units based on detected libs

- tests/wraps/test_trove_classifiers.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/trove_classifiers.py
Fixes: https://github.com/thoth-station/thoth-application/issues/1850
> Derive information from trove classifiers for users

- docs/source/prescription.rst
- tests/prescription/v1/test_wrap.py
- tests/test_pipeline_config.py
- tests/test_report.py
- tests/test_resolver.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/report.py
- thoth/adviser/resolver.py
Fixes: https://github.com/thoth-station/adviser/issues/2014
> Make wraps more lazy

- tests/prescription/v1/test_github_release_notes.py
- thoth/adviser/prescription/v1/github_release_notes.py
> Provide also package name to the GitHub release notes wrap

- docs/source/prescription.rst
> Add demo for considering RPM packages in the runtime environment

- docs/source/prescription.rst
> Add demo for python_packages prescription rule

- thoth/adviser/sieves/thoth_s2i_packages.py
> Add missing parameters to the log messages

- thoth/adviser/cli.py
- thoth/adviser/prescription/v1/prescription.py
... so that we can check what pipeline units were validated and have statistics on their count.
> Show statistics of validated units

- docs/source/prescription.rst
- tests/prescription/v1/test_github_release_notes.py
- tests/prescription/v1/test_pseudonym.py
- tests/prescription/v1/test_sieve.py
- tests/prescription/v1/test_step.py
- thoth/adviser/prescription/v1/github_release_notes.py
- thoth/adviser/prescription/v1/pseudonym.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/unit.py
Related: https://github.com/thoth-station/prescriptions/pull/100
> Support "not" operator when matching Python package index URL

- docs/source/prescription.rst
- tests/prescription/v1/test_github_release_notes.py
- tests/prescription/v1/test_sieve.py
- tests/prescription/v1/test_step.py
- tests/prescription/v1/test_stride.py
- tests/prescription/v1/test_wrap.py
- thoth/adviser/prescription/v1/github_release_notes.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/sieve.py
- thoth/adviser/prescription/v1/step.py
- thoth/adviser/prescription/v1/unit.py
Related: https://github.com/thoth-station/prescriptions/pull/103
> Allow matching dependencies based on the develop flag

- docs/source/prescription.rst
- tests/prescription/v1/test_gh_release_notes.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/gh_release_notes.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
Closes: https://github.com/thoth-station/adviser/issues/1970
> Optimize GitHub release notes pipeline unit wrap

- docs/source/prescription.rst
- thoth/adviser/pipeline_config.py
- thoth/adviser/resolver.py
See:
https://github.com/thoth-station/adviser/blob/5b185ef2ff45efbae6e2fe5a97780bbf4c31fb2b/thoth/adviser/prescription/v1/unit.py#L118-L124
> Fix reporting unit names to logs

- thoth/adviser/prescription/v1/schema.py
If justification is provided, it should be of length 1 and more.
> Be more strict with justification list length

- thoth/adviser/prescription/v1/schema.py
If resolved dependencies list is stated, it should have at least one item to work properly.
> Be more strict about resolved dependencies length

- tests/conftest.py
- tests/prescription/v1/test_unit.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/prescription/__init__.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/prescription/v1/unit_cache.py
Fixes: https://github.com/thoth-station/adviser/issues/2054
> Optimize some parts of should_include by caching them

- thoth/adviser/prescription/v1/unit_cache.py
> Log pre-cached results of should_include if used

- docs/source/prescription.rst
> Update documentation for version spec version requirements

- thoth/adviser/prescription/v1/prescription.py
> Report prescription file that failed to load

- docs/source/prescription.rst
- tests/prescription/v1/test_skip_package_sieve.py
- tests/prescription/v1/test_skip_package_step.py
- tests/prescription/v1/test_step.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/skip_package_sieve.py
- thoth/adviser/prescription/v1/skip_package_step.py
- thoth/adviser/prescription/v1/unit.py
- thoth/adviser/resolver.py
Related: https://github.com/thoth-station/adviser/pull/2050
> Introduce skip package step

- thoth/adviser/prescription/v1/skip_package_step.py
The functionality is shared, do not copy-paste shared logic.
> Reuse code from the parent pipeline step unit

- tests/prescription/v1/test_add_package_step.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/add_package_step.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
This pipeline unit implements adding a package to the resolved state based on matching criteria.
> Introduce a prescription for adding a package to the dependency graph

- thoth/adviser/sieves/rules.py
- thoth/adviser/sieves/solved.py
> Reduce size of the resolution log

- thoth/adviser/boots/solved_software_environment.py
Related: https://github.com/thoth-station/thoth-application/issues/1918
> Suggest alternatives to users if they requested unsolved environment

- docs/source/prescription/steps.rst
> Document injecting dependencies into the dependency graph using prescriptions

- thoth/adviser/dependency_monkey.py
- thoth/adviser/pipeline_config.py
- thoth/adviser/resolver.py
- thoth/adviser/sieves/solved.py
- thoth/adviser/sieves/thoth_s2i_abi_compat.py
- thoth/adviser/steps/cve.py
- thoth/adviser/unit.py
> Make some logging more lazy

- tests/test_product.py
- thoth/adviser/product.py
See https://github.com/thoth-station/micropipenv/issues/186#issuecomment-906160433 for more info.
Closes: https://github.com/thoth-station/adviser/issues/2076
> Fix environment markers handling for direct dependencies

- thoth/adviser/prescription/v1/schema.py
> Fix example shown to users

- .aicoe-ci.yaml
> Re-enable thoth-adviser releases to PyPI

- .prow.yaml
- .s2i/bin/assemble
- .thoth.yaml
- MANIFEST.in
- thoth/adviser/cli.py
- thoth/adviser/prescription/v1/prescription.py
Related: https://github.com/thoth-station/prescriptions/issues/50
> Pickle prescriptions

- docs/source/security.rst
> Mention Security Scorecards in documentation

- Pipfile
- Pipfile.lock
See: https://github.com/python/mypy/issues/11038
> Pin alembic to fix mypy issues

- docs/source/prescription/should_include.rst
- tests/prescription/v1/test_unit.py
- thoth/adviser/pipeline_builder.py
- thoth/adviser/prescription/v1/schema.py
- thoth/adviser/prescription/v1/unit.py
Fixes: https://github.com/thoth-station/adviser/issues/2096
> Configure inclusion of a pipeline unit based on authentication

- tests/sieves/test_thoth_s2i_abi_compat.py
- thoth/adviser/sieves/thoth_s2i_abi_compat.py
Related: https://github.com/thoth-station/thoth-application/pull/2095
Related:  https://github.com/thoth-station/jupyterlab-requirements/issues/544#issuecomment-948384219
Provide information about no ABI present in the runtime environment and fix a bug that filtered packages when the image analysis was not available.
> Fix ABI sieve filtering packages when no image analysis is available

- thoth/adviser/sieves/cve.py
- thoth/adviser/steps/cve.py
Fixes: https://github.com/thoth-station/adviser/issues/2149
> Provide a link to CVE based on info as present in PyPA/advisory-db

- thoth/adviser/state.py
This code is dead as we use [termial-random](https://github.com/thoth-station/termial-random).
> Remove unused termial function

- docs/source/prescription/steps.rst
- tests/prescription/v1/test_group.py
- thoth/adviser/prescription/v1/__init__.py
- thoth/adviser/prescription/v1/group.py
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
Fixes: https://github.com/thoth-station/adviser/issues/1969
> Implement group step prescription

- docs/source/security.rst
> Document Quay security on container images

- thoth/adviser/predictors/random_walk.py
> Fix history cleaning

- docs/source/prescription.rst
- thoth/adviser/prescription/v1/prescription.py
- thoth/adviser/prescription/v1/schema.py
Fixes: https://github.com/thoth-station/adviser/issues/2166
> Introduce metadata in prescriptions

- tests/test_resolver.py
- thoth/adviser/resolver.py
> Do not score user's stack if Pipfile was adjusted

- tests/prescription/v1/test_group.py
- thoth/adviser/prescription/v1/group.py
Fixes an issue causing configuration schema failure.
> Fix configuration schema for group step

- tests/data/constraints/constraints_1.txt
- tests/sieves/test_constraints.py
- thoth/adviser/sieves/constraints.py
Fixes: https://github.com/thoth-station/adviser/issues/2177
> Allow constraints without version identifier

- thoth/adviser/cli.py
Set default platform to be `x86_64`.
> Set default platform if None is explicitly provided

- tests/boots/test_platform.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/platform.py
Related: https://github.com/thoth-station/adviser/pull/2186
> Add a boot that checks if users use supported platform

- docs/source/predictors/temporal_difference_learning.rst
> Fix link to temporal difference learning on Wikipedia

- tests/test_product.py
- thoth/adviser/product.py
Requires: https://github.com/thoth-station/storages/pull/2487/
Fixes: https://github.com/thoth-station/support/issues/149
> Take environment markers that match the given runtime environment

- docs/source/security.rst
> Document Quay Clair as a source of vulnerabilities for containers

- docs/source/security.rst
- pyproject.toml
> Py pyproject.toml

- thoth/adviser/boots/platform.py
> Fix error message produced

- docs/source/integration.rst
> Add a link to thoth-station/cli-examples to docs

- tests/test_thoth_search.py
- thoth/adviser/boots/__init__.py
- thoth/adviser/boots/thoth_search.py
> Provide a way to link to Thoth search UI with results

- tests/sieves/test_experimental_prereleases.py
> Fix typo in class name

- tests/boots/test_thoth_search.py
- tests/wraps/test_thoth_search_package.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/thoth_search_package.py
Add a link to Thoth Search UI for each package resolved.
> Provide a link to Thoth Search UI for each Python package resolved

- tests/sieves/_pulp/__init__.py
- tests/sieves/_pulp/test_index_label.py
- tests/sieves/_pulp/test_no_index_label.py
- thoth/adviser/sieves/__init__.py
- thoth/adviser/sieves/_pulp/__init__.py
- thoth/adviser/sieves/_pulp/index_label.py
- thoth/adviser/sieves/_pulp/no_index_label.py
> Allow filtering Python packages hosted on Pulp

- .prow.yaml
It takes way too long for pre-commit to finish.
> Increase Prow resources

- .pre-commit-config.yaml
Related-to: https://github.com/thoth-station/thoth-application/issues/2111
> Use HTTPS instead of Git in pre-commit

- thoth/adviser/boots/thoth_search.py
Adjust the link to Thoth's search UI used by default.
> Adjust the default link to Thoth search

- docs/source/integration.rst
Link Thoth tutorial published on Red Hat scholars.
> Link tutorial from docs

- tests/wraps/test_thoth_search_package.py
- thoth/adviser/wraps/thoth_search_package.py
Fixes: https://github.com/thoth-station/adviser/issues/2223
> Respect also runtime environment when linking packages in Search

- tests/boots/test_solved_software_environment.py
- thoth/adviser/boots/solved_software_environment.py
> Skip empty lines in solvers configmap

- tests/boots/test_solved_software_environment.py
* make sure `_THOTH_ADVISER_DEPLOYMENT_CONFIGURED_SOLVERS` are properly freed after testing
* test presence of all the relevant stack info items
> Adjust tests when checking for solvers configured

- docs/source/architecture.rst
> Update entries in the architecture docs

- docs/source/developers_guide.rst
> Document how to run Thoth components locally

- tests/sieves/test_filter_index.py
- thoth/adviser/resolver.py
> Fix logging issues based on testsuite

- tests/wraps/test_pytorch_release.py
- thoth/adviser/wraps/__init__.py
- thoth/adviser/wraps/pytorch_release.py
Notify about using PyTorch index.
> Notify when using PyTorch index

- thoth/adviser/resolver.py
Related: #2203 
Implement a simple memory optimizer for the resolver.
> Implement memory optimizer for resolver

- docs/source/deployment.rst
Document how the memory optimizer can be configured.
> Document memory optimizer

- docs/source/deployment.rst
Related: https://github.com/thoth-station/thoth-application/pull/2408
> Add a note about memory optimizer limit

- thoth/adviser/boots/solvers_configured.py
> Normalize operating system version when checking solvers configured

- thoth/adviser/boots/__init__.py
> SolvedSoftwareEnvironmentBoot is mentioned twice in boot listing

- docs/source/predictor.rst
> Fix `context` to `beam` in predictor docs

- .thoth.yaml
- OWNERS
> Add my username to approvers and maintainers

- docs/source/architecture.rst
- No
- No
If I'm not mistaken, the meaning of this phrase should be : "services have SA
assigned **to them**"
The current formulation reads more like the services have done the assigning.
(If it's indeed the intended meaning, please ignore).
> Doc rewording

- docs/source/architecture.rst
> docs: Precision regarding graph-sync-job

- CHANGELOG.md
- thoth/adviser/__init__.py
Release of version 0.56.1
Related-to: #2371 
Manual release pr based on kebechet standards
> Release of version 0.56.1

- .pre-commit-config.yaml
- thoth/adviser/predictors/annealing.py
- thoth/adviser/predictors/mcts.py
- thoth/adviser/resolver.py
> fix mypy failures
