Pipfile.lock

Dependency thoth-storages was used in version 0.0.25, but the current latest version is 0.0.28.

Automatic update of dependency thoth-storages from 0.0.25 to 0.0.28

---

thoth/adviser/python/advise.py
thoth/adviser/python/dependency_graph.py
thoth/adviser/python/dependency_monkey.py

This way we can say dependency monkey to generate software stacks considering
only some indexes (not all registered to Thoth).

Restrict indexes in dependency monkey runs

---

openshift/job-adviser-template.yaml
thoth/adviser/isis.py
thoth/adviser/python/scoring.py

This way we will filter out packages which do not have performance impact from
scored stack.
Fixes: #143

Introduce performance based queries to Isis

---

openshift/job-adviser-template.yaml
openshift/job-dependencyMonkey-template.yaml
openshift/job-provenanceChecker-template.yaml

As we are creating Jobs, OpenShift needs to know from which Registry the images should be pulled, as it assumes docker.io if none is provided.
https://github.com/openshift/origin/pull/13210 might be related.

added the Registry to be used for image pulling to the templates

---

thoth/adviser/python/bin/dependency_graph.py
thoth/adviser/python/solver.py

This way we pick implementation present - simplifies transition to Dgraph.

Do not depend on specific graph adapter from specific module

---

setup.py

Fixes: #233 
The PR contains:
- A method which reads a version from the project library and feeds it to conf.py.
Tested with cmd: `sphinx-build docs/source <destination>`
-  Some Pep8 changes.

Added the method to read version from project library to conf.py

---

thoth/adviser/cli.py
thoth/adviser/python/pipeline/pipeline.py

Depends-On: https://github.com/thoth-station/storages/pull/598
With the transition to Dgraph, there are no flags propagated to the adviser. The reasoning behind it - optimize the query (not to have issues with serialization) and we should move this into the adviser step anyway.

Remove is_solvable flag as done in Dgraph implementation

---

thoth/adviser/python/pipeline/pipeline.py

Otherwise we are querying for any solver results not targeting specific
environment.
Related: https://github.com/thoth-station/adviser/issues/317

Fix transitive query - correctly propagate runtime information

---

setup.py

... so that it's possible to run `pytest` using:
```
pipenv run python3 setup.py test -a "-x -k foo"
```
I see this issue in other packages, we need to update them as well.

Fix handling of additional pytest arguments in setup.py test

---

setup.py
tests/python/dependency_graph/test_adaptation.py
tests/python/pipeline/steps/test_buildtime_error.py
tests/python/pipeline/steps/test_cve.py
tests/python/pipeline/steps/test_limit_latest_versions.py
tests/python/pipeline/steps/test_observation_reduction.py
tests/python/pipeline/steps/test_performance_adjustment.py
tests/python/pipeline/steps/test_prereleases.py
tests/python/pipeline/steps/test_restrict_indexes.py
tests/python/pipeline/steps/test_toolchain.py
tests/python/pipeline/steps/test_unreachable.py
tests/python/pipeline/test_pipeline.py
tests/python/pipeline/test_step_context.py
thoth/adviser/python/dependency_graph/adaptation/graph.py
thoth/adviser/python/pipeline/pipeline.py
thoth/adviser/python/pipeline/step_context.py

This pull request includes multiple changes:
* uses a new way of retrieving data from graph database - according to https://github.com/thoth-station/storages/pull/838
* adjusted testsuite use
* together with https://github.com/thoth-station/storages/pull/838 the memory consumption for recommending a tensorflow stack dropped to something like ~200-250Mi (any TF stack including our AICEoE builds)

Optimize retrieval of transitive dependencies to avoid list copies

---

setup.py

The setuptools package is not recent enough in the base image to use
find_namespace_packages() which were introduced in 40.1.0.

Do not use setuptools.find_namespace_packages() for now

---

thoth/adviser/python/pipeline/pipeline.py

Errors are reported to sentry so let's turn the error reported into a warning,
we will fail adviser anyway - users get notification on what caused the
failure.

Turn error into warning

---

openshift/buildConfig-cached-template.yaml

... so that we get reports to sentry if anything goes wrong during cache build

Add Sentry DSN to build of adviser-cached

---

openshift/buildConfig-cached-template.yaml
openshift/job-adviser-template.yaml
openshift/job-dependencyMonkey-template.yaml
openshift/job-provenanceChecker-template.yaml

use postgresql hostname from thoth configmap
depends-on: https://github.com/thoth-station/thoth-ops/pull/97

use postgresql hostname from thoth configmap

---

tests/python/pipeline/sieves/test_prereleases.py

toml expects all the strings to be formatted with ", otherwise it tries to
parse it as float (?)
Fixes: #434 
Fixes issues when toml substituted contoml in #434

Add spaces to fix toml issues

---

thoth/adviser/cli.py

runtime_environment var should be dict in parameter
The adviser result stores the runtime_environment as str, which causes issue in sync_adviser_result in storages.
```
"result": {
"error": true,
"error_msg": "Unable to resolve all direct dependencies, no versions were found for packages 'daiquiri'",
"parameters": {
"beam_width": -1,
"count": 1,
"library_usage": "{\"version\": \"string\", \"report\": {}}",
"limit": -1,
"limit_latest_versions": -1,
"no_pretty": false,
"output": "http://result-api/api/v1/adviser-result",
"plot_history": null,
"project": {
"requirements": { ...
},
"requirements_locked": { ...
},
"runtime_environment": {
"cuda_version": "9.0",
"hardware": {
"cpu_family": null,
"cpu_model": null
},
"name": "fedora:29-prod",
"operating_system": {
"name": null,
"version": null …
```

runtime_environment var should be dict in parameter

---

tests/test_beam.py
tests/test_context.py
tests/test_resolver.py
thoth/adviser/beam.py
thoth/adviser/context.py
thoth/adviser/resolver.py
thoth/adviser/state.py
thoth/adviser/step.py

This will guarantee each pipeline step is called once on each state making
the pipeline more efficient - especially with complex (too much time
consuming) steps.
Depends-On: #551

Use backtracking to run steps

---

tests/test_resolver.py
thoth/adviser/resolver.py

This PR addresses issue when resolving only products - the context is not bound
to units.

Always bind context

---

openshift/job-adviser-template.yaml
openshift/job-dependencyMonkey-template.yaml
thoth/adviser/run.py

Do not fork adviser by default, perform fork only in the cluster to correctly
propagate issues encountered during an adviser run (e.g. OOM, CPU time
exceeded, ...).

Fork only in the cluster

---

docs/source/developers_guide.rst
docs/source/sieves.rst
docs/source/steps.rst
tests/test_pipeline_config.py
thoth/adviser/pipeline_config.py
thoth/adviser/predictor.py
thoth/adviser/sieve.py
thoth/adviser/step.py

Reverts thoth-station/adviser#619
Let's revert this change - it adds overhead (even thought constant per adviser run). Predictor can use information from `context` that keeps iterations, if such functionality is desired.

Revert "Add new iteration method for sieves and steps"

---

tests/conftest.py
tests/test_context.py
tests/test_product.py
tests/test_resolver.py
thoth/adviser/context.py
thoth/adviser/product.py
thoth/adviser/resolver.py

This addresses optimization where we do not need to query database for
environment markers during the actuall resolution. Markers are obtained during
construction of the final stack as needed based on the pipeline result.

Do not retrieve markers during resolution

---

app.sh

No need to compute all the stacks, the first one found is sufficient to return
(its latest).

Limit number of software stacks to 1 on LATEST

---

tests/test_resolver.py
thoth/adviser/resolver.py

Remove state from the beam when it is really needed - this way we save
O(log(N)) in every resolver iteration in most cases.

Optimize state removal out of beam

---

thoth/adviser/state.py

The current approach seems to be too permissive and older versions are
picked very often.

Use epsilon greedy strategy for picking the latest version

---

openshift/adviser-template.yaml

One task of the inner workflow in the Qeb-Hwt App is failing due to this default value provided in the template. 

No deafult value null for metadata

---

workflows/templates/advise-template.yaml
workflows/templates/finished-webhook-template.yaml

This change is required in order to avoid failure of the inner workflow due to the use of Thamos CLI. 
Related-To: https://github.com/thoth-station/adviser/pull/812

Adviser workflow when using Thamos CLI

---

workflows/templates/finished-webhook-template.yaml

Metadata can have extra parameters not strictly required for GitHub App.
**Context**
```
trigger-finished-webhook:       2020-02-27 10:37:27,787   1 WARNING  thoth.common:275: Logging to a Sentry instance is turned off
trigger-finished-webhook:       2020-02-27 10:37:27,787   1 INFO     thoth.common:297: Logging to rsyslog endpoint is turned off
trigger-finished-webhook:       There are missing keys for GitHub App {'github_event_type': 'thoth_thamos_advise', 'github_check_run_id': 472123141, 'github_installation_id': 6181026, 'github_base_repo_url': 'https://api.github.com/repos/thoth-station/kebechet', 'origin': 'https://github.com/pacospace/kebechet', 'is_s2i': False}
trigger-finished-webhook:       Thamos has run through CLI
```

Use the correct condition for checking parameters

---

thoth/adviser/cli.py

When requriements are passed as a string, the instantiation method tries to open a
file. This causes OSError for large requirements and adviser terminates with a
traceback.

Prevent from OSError when the requirements string is too large

---

tests/test_resolver.py
thoth/adviser/cli.py
thoth/adviser/exceptions.py
thoth/adviser/predictor.py
thoth/adviser/resolver.py
thoth/adviser/run.py

As we are not able to explore the whole state space of all the possible resolved stacks, let's use the user's stack as a base to see if we can find a better stack in comparison to the one user is currently using (based on the lock file submitted to an adviser run).

Introduce user stack scoring as a base for comparision

---

setup.py
thoth/adviser/run.py

This also causes duplicate log messages when JSON logging is turned on.

No need to initialize logging multiple times

---

openshift/job-adviser-template.yaml
openshift/job-dependencyMonkey-template.yaml
thoth/adviser/cli.py
thoth/adviser/run.py
workflows/templates/advise-template.yaml

When running advises for s2i, we do not need to consider development dependencies used for testing the application as the application is deployed. This, in many cases, reduces number of packages considered and the size of the dependency graph explored.

Add option consider/do not consider dev dependencies

---

thoth/adviser/resolver.py

If the last state turns to be a last resolved software stack, the info message
raises error.
Fixes: https://github.com/thoth-station/adviser/issues/897

Fix info message causing issues when the beam is empty

---

tests/predictors/test_latest.py
thoth/adviser/predictors/latest.py

This phase will generate new states out of the initial state. The newly
generated states are always generated from the latest possible direct
dependnecy found in the stack. This way we minimalize a possibility to of
getting stuck during predictions in a local area in the state space where we do
not lead to any final state. This addresses the OOM issue spotted in the stage
environment when resolving latest stacks.

Introduce heat up phase for the latest predictor

---

workflows/templates/advise-template.yaml

The liveness probe expects int otherwise workflow fails. Also, remove parameter as it is not really a parameter.

Fix liveness probe

---

workflows/templates/advise-template.yaml

consistency in workflow while using secrets
The workflow-controller on deployment creates secret named: `argo-artifact-repository-secrets`
https://github.com/thoth-station/ansible-role-argo-workflows/blob/7233110287bb1dc198a446554398929d84e52e09/templates/secrets/secrets.yaml#L4
Feel like secret `argo-artifact-repository` is redundant.

consistency in workflow while using secrets

---

openshift/adviser-template.yaml

Adviser Dev env var added to template
observed in MOC:
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 232, "funcname": "set_template_parameters", "created": 1587582556.219331, "asctime": "2020-04-22 19:09:16,219", "msecs": 219.3310260772705, "relative_created": 502981029.4058323, "process": 61, "message": "Requested to assign parameter 'THOTH_ADVISER_DEV' (value '0') to template but template does not provide the given parameter, forcing..."}
Even though the variable is not in stage, didn't observe any issue as above.

Adviser Dev env var added to template

---

openshift/job-provenanceChecker-template.yaml

Fixes:
- provenance graph sync.
- {"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 232, "funcname": "set_template_parameters",  "message": "Requested to assign parameter 'THOTH_ADVISER_METADATA' (value '{\"origin\": \"None\"}') to template but template does not provide the given parameter, forcing..."}

Sync variable fix for provenance check

---

tests/test_state.py
thoth/adviser/state.py

OrderedDict requires additinal data structures to offer some of the OrderedDict
functionality on top of dict we do not use. Let's rely on Python 3.6
implementation detail that dict is ordered - this will follow more recent Python
implementations (starting Python 3.7 dict is ordered by default).
This simple change saves roughly 36% of memory when computing recommendations
for "tensorflow==*".

Do not use OrderedDict for internal state representation

---

openshift/buildConfig-template.yaml

See https://github.com/sclorg/s2i-python-container/tree/master/3.6#environment-variables for more info.

Disable setup.py processing in s2i builds

---

thoth/adviser/product.py

This patch makes sure each marker will be present in the final output just once
even though multiple packages introduce it.
Fixes: #977

Include each marker of a type just once

---

tests/wraps/test_no_semantic_interposition.py
thoth/adviser/wraps/__init__.py
thoth/adviser/wraps/no_semantic_interposition.py

https://developers.redhat.com/blog/2020/06/25/red-hat-enterprise-linux-8-2-brings-faster-python-3-8-run-speeds/

Introduce a wrap for recommending Python3.8 on RHEL 8.2

---

tests/sieves/test_py36_setuptools.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/py36_setuptools.py

Fixes: https://github.com/thoth-station/solver/issues/350

Introduce a sieve to filter out incompatible setuptools for Python 3.6

---

thoth/adviser/resolver.py

It's annoying to see these messages multiple times in an adviser log. Let's
turn them into debug messages and let pipeline units log relevant parts.

Turn skip package to debug message

---

tests/strides/test_unique_stack.py
thoth/adviser/strides/__init__.py
thoth/adviser/strides/unique_stack.py

This pipeline unit is especially useful for dependency monkey runs when no duplicate software stacks should be resolved in the same dependency monkey run.

Introduce a stride for discarding non-unique stacks

---

thoth/adviser/run.py

Related: https://github.com/thoth-station/adviser/issues/1128
> exit status indication: a 16-bit number, whose low byte is the signal number that killed the process, and whose high byte is the exit status (if the signal number is zero)
https://docs.python.org/3/library/os.html#os.wait

Fix detection of OOM when os.waitpid is used

---

thoth/adviser/steps/security_indicators.py

Fixes: https://github.com/thoth-station/adviser/issues/1145
Pipeline units can be included multiple times. For the SI pipeline unit, there was missing check if the pipeline unit is already included. This caused that adviser was trying to include this pipeline unit on each interation when building the resolution pipeline.

Fix SI step inclusion

---

thoth/adviser/resolver.py

Counting discarded stacks to the limit is not intuitive to the user. This way
user can say "generate N stacks during dependency monkey run" and let the
resolver do its job.

Apply limit of stacks only for the accepted stacks

---

thoth/adviser/predictors/latest.py
thoth/adviser/predictors/random_walk.py
thoth/adviser/state.py

... so that we can supply options to prioritize certain packages during resolution.

Introduce prioritized packages to predictors

---

thoth/adviser/resolver.py

Fix message formatting

---

tests/wraps/test_tf_accuracy.py
thoth/adviser/wraps/__init__.py
thoth/adviser/wraps/tf_accuracy.py

See https://github.com/tensorflow/tensorflow/issues/42045
https://github.com/thoth-station/thoth-station.github.io/pull/132

Notify users about accuracy bug when TensorFlow 2.3 is used

---

thoth/adviser/steps/tensorflow_avx2.py

Fixes: #1022 
- update whiskey lake to the list.
include whiskey_lake micro arch to list of avx2 containing archs

include whiskey_lake microarch to list of avx2 containing archs

---

thoth/adviser/run.py

These messages correspond to the resolution process, not to adviser
specifically.

Correct messages printed to users

---

setup.py
tests/sieves/pandas/__init__.py
tests/sieves/pandas/test_py36_drop.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/pandas/__init__.py
thoth/adviser/sieves/pandas/py36_drop.py

Related: https://github.com/pandas-dev/pandas/pull/35214

Implement a sieve that drops Pandas>=1.2 on Python 3.6

---

tests/steps/tensorflow/test_tf_rm_scipy.py
thoth/adviser/steps/__init__.py
thoth/adviser/steps/tensorflow/__init__.py
thoth/adviser/steps/tensorflow/tf_rm_scipy.py

https://github.com/thoth-station/adviser/pull/1238
https://github.com/thoth-station/adviser/issues/1237
https://github.com/tensorflow/tensorflow/pull/41866
https://github.com/tensorflow/tensorflow/issues/40884
https://github.com/tensorflow/tensorflow/issues/35709
https://github.com/tensorflow/tensorflow/issues/41941
https://github.com/tensorflow/tensorflow/pull/4078

Introduce a step for removing scipy for TF>=2.1<2.3 releases

---

tests/base.py
tests/test_resolver.py

Return pytest.skip if the pipeline unit cannot be verified

---

tests/steps/test_security_indicators.py
thoth/adviser/steps/security_indicators.py

Fixes: https://github.com/thoth-station/adviser/issues/1410
We apply strict standards for security if user asks for secure stack, no high sev high confidence packages allowed.

exclude hc hs if type is secure

---

thoth/adviser/steps/security_indicators.py

Provide schema for security indicators step so that it is registered

---

docs/source/boots.rst
docs/source/pipeline.rst
docs/source/strides.rst
docs/source/unit.rst
docs/source/wraps.rst

Update docs to reflect package_name in boots, strides and wraps

---

thoth/adviser/resolver.py

Keep resolver history only if needed

---

Pipfile
Pipfile.lock
docs/source/deployment.rst
tests/test_state.py
thoth/adviser/cli.py
thoth/adviser/state.py

As resolver performs thousands of rounds when resolving software stacks, it's reasonable to optimize this call which gets called each resolver run. By using this extension, computation is more optimal by circa 25%. See https://gist.github.com/fridex/3794b9cbb35d1b8f523a94ee9d86b8e4

Use C extension for computing termial random

---

docs/source/pseudonyms.rst

Fix documentation for the package_name option in pseudonyms

---

docs/source/wraps.rst
tests/test_report.py
tests/test_resolver.py
thoth/adviser/report.py
thoth/adviser/resolver.py

Call wraps only if products are in the final resolver result

---

thoth/adviser/resolver.py

... users might get confused what "final state" is.

Adjust message logged to reduce confusion

---

liveness.py

... we no longer use `libdependency_graph.so`.

Adjust description in liveness.py

---

liveness.py

... otherwise we can send SIGUSR1 and SIGINT on the first call.

Fix issue when signal is sent in one call in livenenss.py

---

tests/steps/tensorflow/test_tf_21_h5py.py
thoth/adviser/steps/tensorflow/tf_21_h5py.py

h5py==3 causes troubles also on TensorFlow 2.3.1

---

thoth/adviser/run.py

When running `thamos advise` and the adviser fails on the backend side, I see just see an error message such as:
```
'NoneType' object is not subscriptable
```

Improve error message reported to the user

---

Pipfile.lock

Relock so that typing extensions have the right environment marker

---

tests/steps/test_cve.py
thoth/adviser/steps/cve.py

With this change, adviser will report any packages that were removed from the resolution if they would include a security vulnerability. This message is reported only for the security recommendation type.

Add justification to stack info if a package with CVE is avoided

---

tests/sieves/tensorflow/test_tf_240_avx2.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/tensorflow/__init__.py
thoth/adviser/sieves/tensorflow/tf_240_avx2.py
thoth/adviser/steps/tensorflow/tf_avx2.py

Related: #1616
Related: https://github.com/tensorflow/tensorflow/issues/45866 
Related: https://github.com/tensorflow/tensorflow/issues/45744

Implement a sieve that filters out TensorFlow==2.4.0 on non-AVX2 CPU

---

thoth/adviser/wraps/thoth_s2i.py

The pipeline unit is included multiple times. Accidentally.

Fix S2I multiple include pipeline unit

---

tests/wraps/test_thoth_s2i.py
thoth/adviser/wraps/thoth_s2i.py

Fix a bug related to wrong logic of inclusion this pipeline unit - we want to include the unit if Thoth s2i is **not** used.

Invert inclusion logic, include if Thoth s2i is not used

---

tests/sieves/test_experimental_prereleases.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/experimental_prereleases.py

Depends-On: https://github.com/thoth-station/python/pull/334
Related: https://github.com/thoth-station/thoth-application/issues/816
Related: https://github.com/pypa/pipenv/pull/4607
With this change, we will provide experimental support for allowing pre-releases only for selected packages, based on configuration in Pipfile. Users can state which dependencies can be included in a form of pre-releases. An example could be the following Pipfile:
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"
[packages]
tensorflow = ">=2.3"
[dev-packages]
[requires]
python_version = "3.6"
[thoth.allow_prereleases]
tensorflow = true
```
As stated in the configuration, resolver will include pre-releases only for matching TensorFlow=>2.3. As pre-releases apply only for …

Implement a pipeline unit for selective pre-release filtering

---

docs/source/compatibility.rst
docs/source/experimental_features.rst

Related: https://github.com/thoth-station/adviser/pull/1648
Related: https://github.com/thoth-station/thoth-application/issues/816

Document selective pre-releases

---

tests/sieves/test_prereleases.py
thoth/adviser/sieves/prereleases.py

Otherwise the functionality clashes and produces undesired results (no selective pre-releases are done).

Do not enable cut pre-releases step if selective pre-releases are allowed

---

thoth/adviser/sieves/experimental_prereleases.py

```
File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 21, in new_
func
return callback(*args, **kwargs)
File "thoth-adviser", line 494, in advise
return f(get_current_context(), *args, **kwargs)
resolver = Resolver.get_adviser_instance(
File "/opt/app-root/src/thoth/adviser/resolver.py", line 1394, in get_adviser_instance
pipeline = PipelineBuilder.get_adviser_pipeline_config(
File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 457, in get_adviser_pip
eline_config
File "/opt/app-root/src/thoth/adviser/pipeline_builder.py", line 297, in _build_configur
ation
return cls._build_configuration(
unit_configuration = unit_class.should_include(ctx)  # type: ignore
File "/opt/app-root/src/thoth/adviser/sieves/experimental_prereleases.py", line 59, in s …
```

Thoth's additional features can be None

---

tests/sieves/test_legacy_version.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/legacy_version.py

Depends-On: https://github.com/thoth-station/python/pull/343/files
With this pipeline unit, we will filter out legacy versions from the resolution process. The assumption is that these version identifiers are not used for quite some time.

Introduce a sieve to filter out legacy versions from the resolution

---

prepare.py

```
Traceback (most recent call last):
File "/opt/app-root/src/prepare.py", line 101, in <module>
__name__ == "__main__" and main()  # type: ignore
File "/opt/app-root/src/prepare.py", line 40, in main
prepare_adviser(request_file_content)
File "/opt/app-root/src/prepare.py", line 70, in prepare_adviser
with open(os.path.join(_ADVISER_INPUTS_DIR, "runtime_environment.json")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/app-root/src/input/runtime_environment.json'
```

Properly open files for writing in prepare script

---

prepare.py
thoth/adviser/cli.py

Provenance checker accepts only Pipfile/Pipfile.lock

---

tests/sieves/test_experimental_package_index.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/experimental_package_index.py

Related: https://github.com/thoth-station/adviser/pull/1680
With this change, if users disable index adjustments by thoth:
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"
[[source]]
url = "https://thoth-station.ninja/simple"
verify_ssl = true
name = "thoth"
[packages]
tensorflow = {version="*", index="thoth"}
[thoth]
disable_index_adjustment = true
```
TensorFlow will be always resolved from the specified index (in the scenario above, it will be `thoth`).

Add a sieve for filtering packages based on index configured

---

thoth/adviser/sieves/__init__.py

```
File "./thoth-adviser", line 790, in <module>
__name__ == "__main__" and cli()
File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File …
```

Remove invalid entry from sieves

---

thoth/adviser/resolver.py

Depends-On: https://github.com/thoth-station/adviser/pull/1706

Add space after error message

---

MANIFEST.in
tests/boots/test_pipfile_hash.py
tests/data/projects/dev/Pipfile
tests/data/projects/dev/Pipfile.lock
thoth/adviser/boots/pipfile_hash.py

If a user asks for an advise using `thamos advise`, receives a lock file and subsequently performs `thamos advise --dev`, development dependencies are missing in the user's stack.

Remove user's stack if development dependencies are not present

---

thoth/adviser/steps/cve.py

```
2021-03-08 12:35:12,180 thoth.adviser.resolver      WARNING: Step 'CvePenalizationStep' returned score lower than allowed (-1.6), normalizing to -1
```

Normalize score returned from CVE step score

---

thoth/adviser/prescription/v1/schema.py
thoth/adviser/prescription/v1/unit.py

Relax strict match for prescription wrap pipeline units

---

thoth/adviser/prescription/v1/unit.py

Do not enforce operating system to be set for matching

---

docs/source/prescription.rst
thoth/adviser/cli.py
thoth/adviser/prescription/v1/prescription.py

Implement prescription validation with semantics

---

docs/source/index.rst
docs/source/landing_page.rst

The purpose of this page is to create a crossroad for people who want to get involved in Thoth or are seeking information so we can provide a simple link to them. As of now, this summary is more university/internship oriented, but we can extend it as desired.

Add Thoth's landing page

---

thoth/adviser/prescription/v1/unit.py

Report stack info just once in prescription units

---

tests/prescription/v1/test_wrap.py
thoth/adviser/prescription/v1/wrap.py

Keep optimization for prescription wraps with resolved dependencies

---

tests/sieves/test_update.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/update.py

Fixes: https://github.com/thoth-station/adviser/issues/1886
With this pipeline unit, we will be able to perform updates of application stacks as triggered by the internal trigger.

Add update sieve responsible for package updates

---

tests/steps/test_cve.py
thoth/adviser/steps/cve.py

```
2021-06-11 06:36:53,993 thoth.adviser.run           ERROR: The resolution failed as an error was encountered: Failed to run step 'CvePenalizationStep' for Python package ('tensorflow', '1.5.1', 'https://pypi.org/simple'): 'description'
Traceback (most recent call last):
File "/opt/app-root/src/thoth/adviser/resolver.py", line 354, in _run_steps
step_result = step.run(state, package_version)
File "/opt/app-root/src/thoth/adviser/steps/cve.py", line 110, in run
cve_record["description"],
KeyError: 'description'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/app-root/src/thoth/adviser/run.py", line 75, in subprocess_run
report: Union[DependencyMonkeyReport, Report] = resolver.resolve(
File …
```

Fix wrong CVE key obtained

---

thoth/adviser/resolver.py

Turn warning into a debug message, no need to warn in this case.

Turn warning to debug message

---

tests/test_report.py
thoth/adviser/cli.py
thoth/adviser/dm_report.py
thoth/adviser/report.py
thoth/adviser/run.py

Keep pipeline run information only when adviser is run in verbose mode

---

thoth/adviser/sieves/tensorflow/tf_cuda.py

Related: https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0
Closes: https://github.com/thoth-station/adviser/issues/1820

TensorFlow 2.5 is built with CUDA 11.2 support

---

docs/source/prescription.rst
tests/prescription/v1/test_unit.py
thoth/adviser/prescription/v1/schema.py
thoth/adviser/prescription/v1/unit.py

Fixes: https://github.com/thoth-station/adviser/issues/1926
With this change, we have the ability to instrument resolver to include a specific pipeline unit based on Python packages present in the runtime environment. An example can be including a specific pipeline unit to the resolution process when resolving stacks for jupyter notebooks.

Introduce a mechanism for including unit based on Python packages

---

tests/prescription/v1/test_prescription.py
thoth/adviser/prescription/v1/prescription.py

32MiB database of prescriptions loaded in 1.3s instead of the previous 6.4s

Use CLoader to load prescriptions to speed up loading

---

thoth/adviser/sieves/tensorflow/tf_cuda.py

TensorFlow 2.6 uses same CUDA as TensorFlow 2.5, CUDA 11.2

---

tests/test_resolver.py
thoth/adviser/resolver.py

This is a fix when justification information is stated twice in the resulting report. We had an issue report with this, but I cannot find it.
Basically, if a user submits an advice request, we scored the user stack and kept it in the internal structure for further processing. This is, of course, not right - user's stack should be scored and no further actions are needed as the supplied stack is already resolved.

Do not add scored user stack to beam

---

thoth/adviser/prescription/v1/schema.py
thoth/adviser/prescription/v1/wrap.py

```
2021-07-30 11:04:50,574 85598 DEBUG    thoth.adviser.unit:157: Validating configuration for pipeline unit 'thoth.ThothBaseImageWrap'
2021-07-30 11:04:50,574 85598 ERROR    thoth.adviser.unit:161: Failed to validate schema for pipeline unit 'thoth.ThothBaseImageWrap': required key not provided @ data['match']['state']
Traceback (most recent call last):
File "/home/fpokorny/git/thoth-station/adviser/thoth/adviser/unit.py", line 159, in update_configuration
self.CONFIGURATION_SCHEMA(self.configuration)
File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/home/fpokorny/.local/share/virtualenvs/adviser-1eaKppR3/lib/python3.8/site-packages/voluptuous/schema_builde …
```

Make wrap match part optional

---

thoth/adviser/resolver.py

Fixes: https://github.com/thoth-station/adviser/issues/1990

Notify about not verified user's stack

---

thoth/adviser/cli.py
thoth/adviser/prescription/v1/pseudonym.py
thoth/adviser/prescription/v1/sieve.py
thoth/adviser/prescription/v1/step.py

```
black....................................................................Failed
- hook id: black
- files were modified by this hook
reformatted /home/fpokorny/git/thoth-station/adviser/thoth/adviser/cli.py
All done! ✨ 🍰 ✨
1 file reformatted, 217 files left unchanged.
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
thoth/adviser/prescription/v1/pseudonym.py:26:1: F401 'typing.Union' imported but unused
thoth/adviser/prescription/v1/sieve.py:24:1: F401 'typing.Union' imported but unused
thoth/adviser/prescription/v1/step.py:27:1: F401 'typing.Union' imported but unused
```

Fix pre-commit complains

---

thoth/adviser/prescription/v1/unit_cache.py

These messages are not important to users, they should be used only on debug.

Be less verbose about cache hits in prescription unit cache

---

tests/prescription/v1/test_add_package_step.py
tests/prescription/v1/test_boot.py
tests/prescription/v1/test_gh_release_notes.py
tests/prescription/v1/test_pseudonym.py
tests/prescription/v1/test_sieve.py
tests/prescription/v1/test_skip_package_step.py
tests/prescription/v1/test_step.py
tests/prescription/v1/test_stride.py
tests/prescription/v1/test_wrap.py
thoth/adviser/prescription/v1/add_package_step.py
thoth/adviser/prescription/v1/boot.py
thoth/adviser/prescription/v1/gh_release_notes.py
thoth/adviser/prescription/v1/pseudonym.py
thoth/adviser/prescription/v1/sieve.py
thoth/adviser/prescription/v1/skip_package_sieve.py
thoth/adviser/prescription/v1/skip_package_step.py
thoth/adviser/prescription/v1/step.py
thoth/adviser/prescription/v1/stride.py
thoth/adviser/prescription/v1/unit.py
thoth/adviser/prescription/v1/wrap.py

Fixes: https://github.com/thoth-station/adviser/issues/2098

Introduce prescription run to make sure each prescription reports once

---

tests/sieves/test_cve.py
tests/steps/test_cve.py
thoth/adviser/sieves/__init__.py
thoth/adviser/sieves/cve.py
thoth/adviser/steps/cve.py

With this change, packages with CVEs will be filtered out sooner in the resolution process. This will make sure the security-based recommendations will be more optimal when finding a software stack without any security vulnerabilities.

Introduce a CVE sieve

---

tests/prescription/v1/test_unit.py
thoth/adviser/prescription/v1/unit.py

For example, the following prescription:
```yaml
runtime_environments:
operating_systems:
- name: rhel
```
should match:
```yaml
runtime_environment:
operating_system:
name: rhel
version: "8"
```

Fix matching operating system in prescriptions

---

tests/boots/test_cve_timestamp.py
thoth/adviser/boots/__init__.py
thoth/adviser/boots/cve_timestamp.py

Fixes: https://github.com/thoth-station/adviser/issues/2142
Users of Thoth will have information about the last CVE update so that they are aware how old the CVE information provided is.

Provide information about last CVE update to users

---

tests/boots/test_environment_info.py
thoth/adviser/boots/environment_info.py

As of now, recommendation type in placed between other environment information that might be not nice from UX point of view:
```
https://thoth-station.ninja/j/py_version                   │ No version of Python specified explicitly, assigning the one found in Thoth's      │ -            │ ⚠️ WARNING  
│ configuration: '3.6'                                                               │              │            
https://thoth-station.ninja/j/env                          │ Resolving for runtime environment named 'my_project'                               │ -            │ ✔️ INFO     
https://thoth-station.ninja/j/env                          │ Resolving for operating system 'rhel' in version '8.0'                             │ -            │ -          
https://thoth-station.ninja/j/env …
```

Move recommendation type information more to the top

---

thoth/adviser/boots/fully_specified_environment.py

The string concatenation did not happen, there was printed just the very first line.

Fix reporting fully specified environment

---

thoth/adviser/resolver.py

```
Link                                              │ Message                                                                                                                  │ Package name           │ Type       
═══════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪════════════════════════╪═══════════ 
https://thoth-station.ninja/j/solve_direct        │ No versions were found for direct dependency 'foo-someunknownpackage'; operating system 'rhel' in OS version '8' for     │ -                      │ ❌ ERROR   
│ Python in version '3.8' using platform 'linux-x86_64'                                                                    │                        │ …
```

Propagate information about package name when not solved

---

tests/boots/test_version_check.py
thoth/adviser/boots/__init__.py
thoth/adviser/boots/version_check.py

Warn users if they provide too lax version range specifiers

---

tests/boots/test_environment_info.py
thoth/adviser/boots/environment_info.py

```
https://thoth-station.ninja/j/env                                      │ Resolving for runtime environment named 'ubi8'                         │ ✔️ INFO     
https://thoth-station.ninja/j/env                                      │ Resolving for operating system 'rhel' in version '8'                   │ -          
https://thoth-station.ninja/j/env                                      │ Resolving for Python version '3.6'                                     │ ✔️ INFO     
```

Add missing message type to environment info

---

thoth/adviser/boots/__init__.py

Adviser reports environments as EOL if users supply a minor version of UBI/RHEL releases. This change makes sure EOL is not reported in cases when minor versions are used as they are adjusted by `RHELVersionBoot`:
```
https://thoth-station.ninja/j/eol_env             │ Runtime environment used is no longer supported, it is recommended to switch to another     │ ⚠️ WARNING  
│ runtime environment                                                                         │            
```

Place EOL warning boot after RHELVersionBoot

---

docs/source/integration.rst

https://github.com/thoth-station/kebechet/pull/850
Update the link to Kebechet Managers now that this documentation is available on the website.

Update the link to Kebechet managers documentation

---

tests/boots/test_solved_software_environment.py
thoth/adviser/boots/solved_software_environment.py

Related to #2245 
Get environments from solvers configmap instead of the database and adjust tests to match the suggested implementation

Get environments from solvers configmap and fix tests for solved software environments

---

app.sh

It might be not needed to score more than one software stack when the recommendation type is set to security. The very first secure software stack found can be returned.

Obtian the very first secure software stack

---

thoth/adviser/wraps/thoth_search_package.py

We have moved from `thoth-search` to just `search`.

Change link to Thoth Search for a package

---

docs/source/dependency_monkey.rst

- No
This subcommand no longer exists.

Remove documentation on `submit-amun` thoth-adviser CLI subcommand

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/kebechet_update.md
.github/ISSUE_TEMPLATE/major-release.md
.github/ISSUE_TEMPLATE/minor-release.md
.github/ISSUE_TEMPLATE/patch-release.md
.github/ISSUE_TEMPLATE/redeliver_container_image.md
.github/PULL_REQUEST_TEMPLATE.md

The trigger for this is that the `needs-triage` label is no longer in widespread use (see https://github.com/thoth-station/thoth-application/issues/2359)
but the templates are still adding it to new issues in this repo (see e.g. #2308 from yesterday).
- No
Update the GitHub issue and PR templates taking the current content from the [template repo](https://github.com/thoth-station/template-project/tree/master/.github)

Update the GitHub issue templates

---

tests/boots/test_labels.py
tests/sieves/test_cve.py
tests/test_unit.py
thoth/adviser/boots/labels.py
thoth/adviser/sieves/cve.py
thoth/adviser/steps/cve.py
thoth/adviser/unit.py

Related: https://github.com/thoth-station/adviser/issues/2342
- No
Allow users to specify `allow-cve` label in their `.thoth.yaml` configuration file or by supplying `--labels` option to Thamos CLI. This feature allows specifying which CVEs are acceptable in the application stack. Example:
```yaml
labels:
allow-cve: PYSEC-2021-94,PYSEC-2021-2
```

Implement allowing certain CVEs being present in the application stack

---

.pre-commit-config.yaml
.prow.yaml
tests/prescription/v1/test_add_package_step.py
tests/prescription/v1/test_gh_release_notes.py
tests/prescription/v1/test_group.py
tests/sieves/test_experimental_conf_index.py
thoth/adviser/boots/environment_info.py
thoth/adviser/boots/thoth_search.py
thoth/adviser/predictor.py
thoth/adviser/predictors/annealing.py
thoth/adviser/predictors/mcts.py
thoth/adviser/prescription/v1/unit.py
thoth/adviser/resolver.py

Fixes: https://github.com/thoth-station/support/issues/219
- No
- Yes (if a patch release is desired, although this is a minor bugfix)
Fix the URL that points to the Thoth Search web UI.
The correct path is `/search/advise/:id:`, e.g. https://thoth-station.ninja/search/advise/adviser-220520135456-693dce14c5adfe00/summary
Also, this PR includes an update to the pre-commit configuration, and related changes that pre-commit reported during a local run.

Fix the URL path when pointing to the search Web UI

---

.pre-commit-config.yaml
.thoth.yaml
OWNERS
thoth/adviser/unit.py

https://github.com/thoth-station/adviser/issues/2354#issuecomment-1171405051
- No
- No
This removes the `maintainers` section from `.thoth.yaml`.
Kebechet will pick up from the approvers list in `OWNERS`, removing redundancy and inconsistency.
Also updating the approvers list to include maintainers from `.thoth.yaml`

Remove the maintainers section from .thoth.yaml

---

docs/source/pipeline.rst

The plot and the text following this sentence clearly express it's 25000
rather than 2500

Fix a typo

---

.flake8
.pre-commit-config.yaml
pyproject.toml

This allow to use the flake8 as part of the pre-commit hooks *and* with
other tool (in particular, the python-lsp-server).

Moves flake8 config into a dedicated file

---

.pre-commit-hooks.yaml
thoth/adviser/cli.py
thoth/adviser/prescription/v1/prescription.py

- Make Presciption.validate error tolerant and report detailed errors
- Add pre-commit mode to validate-prescriptions and explicit files passing
- Pre-commit hook definition
closes #2391
needs thoth-station/python#489 + a release to work
- No
- Yes

turn validate-prescriptions into pre-commit hook

---

Pipfile
Pipfile.lock

We previously relied on amun being a transitive dependecy (from
thoth-storages).
This avoids things breaking when upstream (thoth-storages in that cases)
deps change.

Add amun as direct dep.

---

tests/boots/test_prescription_release.py
tests/prescription/v1/test_prescription.py

There was a slight change in the Prescription.load API, adjusting the
tests (Prescription.load does not appear to be used anywhere else)
- No
- Yes

Fix test failures introduced by 613da05d

---

.thoth.yaml

Closes #2422
Related to #2411
- No
- No
Disable Kebechet's [pipfile-requirements manager](https://thoth-station.ninja/docs/developers/kebechet/managers/pipfile_requirements.html) in the repo, as there is no `requirements.txt` here anymore.

Disable Kebechet pipfile-requirements manager
